import { test } from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
async function compile(entry){const r=await build({entryPoints:[entry],bundle:true,platform:'node',format:'cjs',write:false,plugins:[{name:'fallback',setup(b){b.onResolve({filter:/^\.\/router-company-admin-demo-ui$/},()=>({path:'legacy',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export default {fetch:async()=>new Response("Legacy",{status:500})}'}));}}]});const m={exports:{}};new Function('require','module','exports',r.outputFiles[0].text)(require,m,m.exports);return m.exports;}
const analytics=await compile('worker/dashboard-analytics.ts');
const navigation=(await compile('worker/router-company-admin-safe.ts')).default;
const actions=await compile('worker/router-company-admin-demo-ui-v2.ts');
const d={machines:[{fleet:'A',site:'North',nextService:250,hours:260},{fleet:'B',site:'South',nextService:500,hours:460}],settings:{dailyTarget:100},production:[{reportDate:'2026-10-01',fleet:'A',shiftHours:10,plannedDowntime:0,unplannedDowntime:2,operatingHours:4,tonnes:30},{reportDate:'2026-10-02',fleet:'A',shiftHours:20,plannedDowntime:0,unplannedDowntime:0,operatingHours:10,tonnes:70},{reportDate:'2026-10-01',fleet:'B',shiftHours:10,plannedDowntime:0,unplannedDowntime:0,operatingHours:10,tonnes:50},{reportDate:'2026-09-30',fleet:'A',shiftHours:24,tonnes:999}],events:[{fleet:'A',system:'Engine',downtime:6,openedAt:'2026-10-01'},{fleet:'A',system:'Engine',downtime:2,openedAt:'2026-10-02'},{fleet:'A',system:'Tyres',downtime:2,openedAt:'2026-10-02'},{fleet:'B',system:'Tyres',downtime:100,openedAt:'2026-10-01'}]};
const filters=analytics.dashboardFilters(new URL('https://x/?from=2026-10-01&to=2026-10-02&site=North'));
test('site/date filters and weighted KPIs use the same records',()=>{const a=analytics.analyseDashboard(d,filters);assert.equal(a.production.length,2);assert.equal(a.tonnes,100);assert.equal(a.availability,28/30*100);assert.equal(a.utilisation,50);assert.equal(a.events.length,3);assert.deepEqual(a.repeat,[['A · Engine',2]]);assert.equal(a.maintenance[0].remaining,-10);});
test('Pareto is descending and cumulative includes all categories',()=>{const rows=analytics.analyseDashboard(d,filters).causePareto;assert.deepEqual(rows,[{label:'Engine',hours:8,cumulative:80},{label:'Tyres',hours:2,cumulative:100}]);const svg=analytics.paretoChart('Causes',rows);assert.match(svg,/Orange line: cumulative percentage/);assert.match(svg,/80\.0%/);assert.match(svg,/100\.0%/);});
test('empty periods have unknown KPIs and explicit chart empty states',()=>{const a=analytics.analyseDashboard(d,{...filters,from:'2026-11-01',to:'2026-11-30'});assert.equal(a.availability,null);assert.equal(a.utilisation,null);assert.match(analytics.chart('Trend',[],[]),/No data for this period/);});
test('invalid and reversed date filters are normalized',()=>{assert.deepEqual(analytics.dashboardFilters(new URL('https://x/?from=2026-10-03&to=2026-10-01')),{from:'2026-10-01',to:'2026-10-03',site:'',fleet:''});assert.equal(analytics.dashboardFilters(new URL('https://x/?from=2026-02-31'),new Date('2026-10-03')).from,'2026-10-01');});
function environment(role){const writes=[];return {writes,DB:{prepare(sql){let binds=[];return {bind(...v){binds=v;return this},async run(){writes.push({sql,binds});return {success:true}},async all(){if(sql.includes('FROM machines'))return {results:d.machines};if(sql.includes('FROM events'))return {results:d.events};if(sql.includes('FROM production_records'))return {results:d.production};return {results:[]}},async first(){if(sql.includes('FROM contractor_sessions'))return {companyId:3,accountId:8,email:'user@example.com',fullName:'User',role,accountStatus:'active',sessionExpires:'2099-01-01',companyName:'Test Mine',licenceStatus:'active',licenceExpires:'2099-01-01'};if(sql.includes('company_settings'))return d.settings;return null}}}}};}
const headers={cookie:'sas_contractor_v2=test'};
test('Admin and Engineer see distinct dashboard actions and all charts',async()=>{for(const role of ['company_admin','engineer']){const r=await navigation.fetch(new Request('https://x/contractor?from=2026-10-01&to=2026-10-02',{headers}),environment(role),{});assert.equal(r.status,200);const html=await r.text();assert.match(html,new RegExp(role==='engineer'?'Engineer Dashboard':'Admin Dashboard'));for(const title of ['Availability and utilisation trends','Production actual versus target','Downtime trend','Downtime Pareto by cause','Downtime Pareto by machine'])assert.ok(html.includes(title));assert.equal(html.includes('Capture / import daily report'),role==='company_admin');assert.ok(html.includes('data-nav="recommendations"'));}});
test('filtered CSV exports only selected company equipment and dates',async()=>{const r=await navigation.fetch(new Request('https://x/contractor?from=2026-10-01&to=2026-10-02&fleet=A&download=csv',{headers}),environment('engineer'),{});const csv=await r.text();assert.match(r.headers.get('content-type'),/text\/csv/);assert.ok(!csv.includes('"B"'));assert.ok(!csv.includes('999'));assert.equal(csv.split('\r\n').length,3);});
async function post(env,values,origin='https://x'){const csrf=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test'))).toString('hex');return actions.handleEngineeringActions(new Request('https://x/company-admin/recommendations',{method:'POST',headers:{...headers,origin},body:new URLSearchParams({csrf,...values})}),env);}
test('Engineer creates a recommendation with company and author bound on server',async()=>{const env=environment('engineer');assert.equal((await post(env,{action:'create',recommendation:'Inspect recurring engine faults',priority:'high'})).status,303);const insert=env.writes.find(w=>w.sql.startsWith('INSERT'));assert.deepEqual(insert.binds.slice(0,6),[3,8,'User','','Inspect recurring engine faults','high']);});
test('recommendation edits cannot target another company or author',async()=>{const env=environment('engineer');assert.equal((await post(env,{action:'edit',id:'999',recommendation:'Changed'})).status,404);assert.ok(!env.writes.some(w=>w.sql.startsWith('UPDATE')));});
test('Engineer cannot respond as Admin; cross-origin and missing CSRF rejected',async()=>{assert.equal((await post(environment('engineer'),{action:'respond',status:'completed',response:'Done'})).status,403);assert.equal((await post(environment('engineer'),{action:'create',recommendation:'Test'},'https://evil.example')).status,403);assert.equal((await post(environment('engineer'),{action:'create',recommendation:'Test',csrf:''})).status,403);});
test('legacy source-data writes blocked for Engineer while Admin remains allowed',async()=>{for(const path of ['/company-admin/daily/manual','/api/contractor/fleet','/role/action','/api/contractor/production','/telemetry/connections']){const req=new Request('https://x'+path,{method:'POST',headers});assert.equal((await actions.guardEngineerWrites(req,environment('engineer'))).status,403);assert.equal(await actions.guardEngineerWrites(req,environment('company_admin')),null);}});
test('Admin response stores progress against the signed-in company',async()=>{const env=environment('company_admin'),prepare=env.DB.prepare;env.DB.prepare=sql=>{const statement=prepare(sql);if(sql.startsWith('SELECT id FROM engineering_recommendations_v1'))statement.first=async()=>({id:42});return statement;};assert.equal((await post(env,{action:'respond',id:'42',status:'completed',response:'Service completed and verified'})).status,303);const update=env.writes.find(w=>w.sql.startsWith('UPDATE'));assert.equal(update.binds[0],'completed');assert.equal(update.binds[1],'Service completed and verified');assert.equal(update.binds[6],42);assert.equal(update.binds[7],3);});
const insights=await compile('worker/engineering-insights.ts');
test('MTBF counts failure events only, MTTR includes only repairs closed in period',()=>{const production=[{reportDate:'2026-10-01',operatingHours:100}],events=[{eventType:'breakdown',openedAt:'2026-10-01',status:'closed',closedAt:'2026-10-02',downtime:4},{eventType:'breakdown',openedAt:'2026-10-03',status:'open',downtime:12},{eventType:'service',openedAt:'2026-10-02',status:'closed',closedAt:'2026-10-02',downtime:6},{eventType:'breakdown',openedAt:'2026-09-30',status:'closed',closedAt:'2026-10-02',downtime:2}];const r=insights.reliability(production,events,'2026-10-01','2026-10-31');assert.equal(r.mtbf,50);assert.equal(r.mttr,3);assert.equal(r.repairs,2);assert.equal(insights.reliability(production,[],'2026-10-01','2026-10-31').mtbf,null);assert.equal(insights.reliabilityTrend(production,events,'2026-10-01','2026-10-31')[0].mtbf,50);});
test('quality checks flag duplicates, decreasing meters and impossible shift totals without mutations',()=>{const p=[{id:1,fleet:'A',reportDate:'2026-10-01',shiftHours:10,operatingHours:9,unplannedDowntime:2}],daily=[{id:1,fleet:'A',reportDate:'2026-10-01',hourMeterStart:100,hourMeterEnd:105,duration:5},{id:2,fleet:'A',reportDate:'2026-10-02',hourMeterStart:103,hourMeterEnd:102,duration:1},{id:3,fleet:'A',reportDate:'2026-10-02',hourMeterStart:103,hourMeterEnd:102,duration:1}];const before=JSON.stringify([p,daily]),issues=insights.qualityIssues(p,daily);assert.ok(issues.some(r=>r.issue.includes('exceed scheduled')));assert.ok(issues.some(r=>r.issue.includes('Possible duplicate')));assert.ok(issues.some(r=>r.issue.includes('below its start')));assert.ok(issues.some(r=>r.issue.includes('decreased')));assert.equal(JSON.stringify([p,daily]),before);});
test('completed recommendations are never overdue and due-today remains on time',()=>{assert.equal(insights.overdueRecommendation({due_date:'2026-10-02',status:'open'},'2026-10-03'),true);assert.equal(insights.overdueRecommendation({due_date:'2026-10-03',status:'open'},'2026-10-03'),false);assert.equal(insights.overdueRecommendation({due_date:'2026-10-02',status:'completed'},'2026-10-03'),false);});
test('Demo uses synthetic data, never reads company records or exposes account identity',async()=>{for(const role of ['engineer','company_admin']){const env=environment(role),prepare=env.DB.prepare;env.DB.prepare=sql=>{if(/FROM (machines|events|production_records|contractor_accounts|engineering_recommendations_v1)/.test(sql))throw new Error('Demo read live records: '+sql);return prepare(sql);};const r=await navigation.fetch(new Request('https://x/contractor?view=demo',{headers}),env,{});assert.equal(r.status,200);const html=await r.text();assert.match(html,/DEMO MODE: synthetic sample data only/);assert.match(html,/DEMO-01/);assert.ok(!html.includes('Test Mine'));assert.ok(!html.includes('user@example.com'));assert.ok(!html.includes('action="/company-admin/analytics-settings"'));}});
test('Machine history opens company equipment, rejects an unknown fleet and links read-only records',async()=>{for(const role of ['engineer','company_admin']){const r=await navigation.fetch(new Request('https://x/contractor?view=machine-history&fleet=A',{headers}),environment(role),{});const body=await r.text();assert.equal(r.status,200);assert.match(body,/Daily report history/);assert.match(body,/Maintenance work history/);assert.ok(!body.includes('<td>B</td>'));const unknown=await navigation.fetch(new Request('https://x/contractor?view=machine-history&fleet=OTHER-COMPANY',{headers}),environment(role),{});assert.equal(unknown.status,404);}});
test('Engineer cannot set downtime cost; Admin validates and saves company-specific rate',async()=>{async function ratePost(role,rate){const csrf=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test'))).toString('hex'),env=environment(role);const r=await actions.handleEngineeringActions(new Request('https://x/company-admin/analytics-settings',{method:'POST',headers:{...headers,origin:'https://x'},body:new URLSearchParams({csrf,rate})}),env);return {r,env};}assert.equal((await ratePost('engineer','100')).r.status,403);assert.equal((await ratePost('company_admin','-1')).r.status,400);assert.equal((await ratePost('company_admin','NaN')).r.status,400);const {r,env}=await ratePost('company_admin','2500');assert.equal(r.status,303);const insert=env.writes.find(w=>w.sql.startsWith('INSERT INTO company_analytics_settings'));assert.deepEqual(insert.binds.slice(0,3),[3,2500,8]);});
test('Admin saves recommendation owner and deadline; invalid dates rejected',async()=>{const env=environment('company_admin'),prepare=env.DB.prepare;env.DB.prepare=sql=>{const statement=prepare(sql);if(sql.startsWith('SELECT id FROM engineering_recommendations_v1'))statement.first=async()=>({id:42});return statement;};assert.equal((await post(env,{action:'respond',id:'42',status:'in-progress',response:'Assigned for inspection',assigneeName:'Workshop lead',dueDate:'2026-10-06'})).status,303);const update=env.writes.find(w=>w.sql.startsWith('UPDATE'));assert.equal(update.binds[4],'Workshop lead');assert.equal(update.binds[5],'2026-10-06');assert.equal((await post(env,{action:'respond',id:'42',status:'open',response:'Check',dueDate:'2026-02-31'})).status,400);});
test('Demo CSV is labelled as synthetic sample data',async()=>{const r=await navigation.fetch(new Request('https://x/contractor?view=demo&download=csv',{headers}),environment('engineer'),{});assert.match(r.headers.get('content-disposition'),/demo-sample-performance/);const csv=await r.text();assert.match(csv,/DEMO SAMPLE DATA/);assert.match(csv,/DEMO-01/);assert.ok(!csv.includes('Test Mine'));});
test('recommendation column migration preserves existing rows and repeats safely',()=>{const source=require('node:fs').readFileSync('worker/router-company-admin-demo-ui-v2.ts','utf8'),sql=source.match(/CREATE TABLE IF NOT EXISTS engineering_recommendations_v1\([^`]+/)[0];const result=require('node:child_process').spawnSync('python',['-c',`import sqlite3,sys,json
sql=json.loads(sys.stdin.read())
db=sqlite3.connect(':memory:')
old=sql.replace(",assignee_name TEXT NOT NULL DEFAULT '',due_date TEXT NOT NULL DEFAULT ''",'')
db.execute(old)
db.execute("INSERT INTO engineering_recommendations_v1(company_id,author_id,author_name,recommendation,created_at,updated_at) VALUES(3,8,'Engineer','Inspect engine','2026-10-01','2026-10-01')")
for _ in range(2):
 db.execute(sql)
 columns=[r[1] for r in db.execute('PRAGMA table_info(engineering_recommendations_v1)')]
 for name in ['assignee_name','due_date']:
  if name not in columns: db.execute("ALTER TABLE engineering_recommendations_v1 ADD COLUMN "+name+" TEXT NOT NULL DEFAULT ''")
assert db.execute('SELECT company_id,recommendation,assignee_name,due_date FROM engineering_recommendations_v1').fetchall()==[(3,'Inspect engine','','')]
print('preserved')`],{input:JSON.stringify(sql),encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/preserved/);});
