import { test } from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
async function compile(entry){const r=await build({entryPoints:[entry],bundle:true,platform:'node',format:'cjs',write:false,plugins:[{name:'fallback',setup(b){b.onResolve({filter:/^\.\/router-company-admin-demo-ui$/},()=>({path:'legacy',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export default {fetch:async()=>new Response("Legacy",{status:500})}'}));}}]});const m={exports:{}};new Function('require','module','exports',r.outputFiles[0].text)(require,m,m.exports);return m.exports;}
const analytics=await compile('worker/dashboard-analytics.ts');
const navigation=(await compile('worker/router-company-admin-safe.ts')).default;
const actions=await compile('worker/router-company-admin-demo-ui-v2.ts');
const d={machines:[{fleet:'A',site:'North',nextService:250,hours:260},{fleet:'B',site:'South',nextService:500,hours:460}],settings:{dailyTarget:100},production:[{reportDate:'2026-10-01',fleet:'A',shiftHours:10,plannedDowntime:0,unplannedDowntime:2,operatingHours:4,tonnes:30},{reportDate:'2026-10-02',fleet:'A',shiftHours:20,plannedDowntime:0,unplannedDowntime:0,operatingHours:10,tonnes:70},{reportDate:'2026-10-01',fleet:'B',shiftHours:10,plannedDowntime:0,unplannedDowntime:0,operatingHours:10,tonnes:50},{reportDate:'2026-09-30',fleet:'A',shiftHours:24,tonnes:999}],events:[{fleet:'A',system:'Engine',downtime:6,openedAt:'2026-10-01'},{fleet:'A',system:'Engine',downtime:2,openedAt:'2026-10-02'},{fleet:'A',system:'Tyres',downtime:2,openedAt:'2026-10-02'},{fleet:'B',system:'Tyres',downtime:100,openedAt:'2026-10-01'}]};
const filters=analytics.dashboardFilters(new URL('https://x/?from=2026-10-01&to=2026-10-02&site=North'));
test('site/date filters and weighted KPIs use the same records',()=>{const a=analytics.analyseDashboard(d,filters);assert.equal(a.production.length,2);assert.equal(a.tonnes,100);assert.equal(a.availability,28/30*100);assert.equal(a.utilisation,50);assert.equal(a.events.length,3);assert.deepEqual(a.repeat,[['A · Engine',2]]);assert.equal(a.maintenance[0].remaining,-10);});
test('Pareto is descending and cumulative includes all categories',()=>{const rows=analytics.analyseDashboard(d,filters).causePareto;assert.deepEqual(rows,[{label:'Engine',hours:8,cumulative:80},{label:'Tyres',hours:2,cumulative:100}]);const svg=analytics.paretoChart('Causes',rows);assert.match(svg,/Orange line: cumulative percentage/);assert.match(svg,/80\.0%/);assert.match(svg,/100\.0%/);});
test('empty periods have unknown KPIs and explicit chart empty states',()=>{const a=analytics.analyseDashboard(d,{...filters,from:'2026-11-01',to:'2026-11-30'});assert.equal(a.availability,null);assert.equal(a.utilisation,null);assert.match(analytics.chart('Trend',[],[]),/No data for this period/);});
test('invalid and reversed date filters are normalized',()=>{assert.deepEqual(analytics.dashboardFilters(new URL('https://x/?from=2026-10-03&to=2026-10-01')),{from:'2026-10-01',to:'2026-10-03',site:'',fleet:''});assert.equal(analytics.dashboardFilters(new URL('https://x/?from=2026-02-31'),new Date('2026-10-03')).from,'2026-10-01');});
function environment(role){const writes=[];return {writes,DB:{prepare(sql){let binds=[];return {bind(...v){binds=v;return this},async run(){writes.push({sql,binds});return {success:true}},async all(){if(sql.includes('FROM machines'))return {results:d.machines};if(sql.includes('FROM events'))return {results:d.events};if(sql.includes('FROM production_records'))return {results:d.production};return {results:[]}},async first(){if(sql.includes('FROM contractor_sessions'))return {companyId:3,accountId:8,email:'user@example.com',fullName:'User',role,accountStatus:'active',sessionExpires:'2099-01-01',companyName:'Test Mine',licenceStatus:'active',licenceExpires:'2099-01-01'};if(sql.includes('company_settings'))return d.settings;return null}}}}};}
const headers={cookie:'sas_contractor_v2=test'};
test('Admin and Engineer see distinct dashboard actions and all charts',async()=>{for(const role of ['company_admin','engineer']){const r=await navigation.fetch(new Request('https://x/contractor?from=2026-10-01&to=2026-10-02',{headers}),environment(role),{});assert.equal(r.status,200);const html=await r.text();assert.match(html,new RegExp(role==='engineer'?'Engineer Dashboard':'Admin Dashboard'));for(const title of ['Availability and utilisation trends','Production actual versus target','Downtime trend','Downtime Pareto by cause','Downtime Pareto by machine'])assert.ok(html.includes(title));assert.equal(html.includes('Capture / import daily report'),role==='company_admin');assert.ok(html.includes('data-nav="recommendations"'));}});
test('filtered CSV exports only selected company equipment and dates',async()=>{const r=await navigation.fetch(new Request('https://x/contractor?from=2026-10-01&to=2026-10-02&fleet=A&download=csv',{headers}),environment('engineer'),{});const csv=await r.text();assert.match(r.headers.get('content-type'),/text\/csv/);assert.ok(!csv.includes('"B"'));assert.ok(!csv.includes('999'));assert.equal(csv.split('\r\n').length,3);});
async function post(env,values,origin='https://x'){const csrf=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test'))).toString('hex');return actions.handleEngineeringActions(new Request('https://x/company-admin/recommendations',{method:'POST',headers:{...headers,origin},body:new URLSearchParams({csrf,...values})}),env);}
test('Engineer creates a recommendation with company and author bound on server',async()=>{const env=environment('engineer');assert.equal((await post(env,{action:'create',recommendation:'Inspect recurring engine faults',priority:'high'})).status,303);const insert=env.writes.find(w=>w.sql.startsWith('INSERT'));assert.deepEqual(insert.binds.slice(0,6),[3,8,'User','','Inspect recurring engine faults','high']);});
test('recommendation edits cannot target another company or author',async()=>{const env=environment('engineer');assert.equal((await post(env,{action:'edit',id:'999',recommendation:'Changed'})).status,404);assert.ok(!env.writes.some(w=>w.sql.startsWith('UPDATE')));});
test('Engineer cannot respond as Admin; cross-origin and missing CSRF rejected',async()=>{assert.equal((await post(environment('engineer'),{action:'respond',status:'completed',response:'Done'})).status,403);assert.equal((await post(environment('engineer'),{action:'create',recommendation:'Test'},'https://evil.example')).status,403);assert.equal((await post(environment('engineer'),{action:'create',recommendation:'Test',csrf:''})).status,403);});
test('legacy source-data writes blocked for Engineer while Admin remains allowed',async()=>{for(const path of ['/company-admin/daily/manual','/api/contractor/fleet','/role/action','/api/contractor/production','/telemetry/connections']){const req=new Request('https://x'+path,{method:'POST',headers});assert.equal((await actions.guardEngineerWrites(req,environment('engineer'))).status,403);assert.equal(await actions.guardEngineerWrites(req,environment('company_admin')),null);}});
test('Admin response stores progress against the signed-in company',async()=>{const env=environment('company_admin'),prepare=env.DB.prepare;env.DB.prepare=sql=>{const statement=prepare(sql);if(sql.startsWith('SELECT id FROM engineering_recommendations_v1'))statement.first=async()=>({id:42});return statement;};assert.equal((await post(env,{action:'respond',id:'42',status:'completed',response:'Service completed and verified'})).status,303);const update=env.writes.find(w=>w.sql.startsWith('UPDATE'));assert.equal(update.binds[0],'completed');assert.equal(update.binds[1],'Service completed and verified');assert.equal(update.binds[4],42);assert.equal(update.binds[5],3);});
