import currentApp from "./router-role-history";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime:number; cron:string; noRetry():void; }
interface Env { DB:D1Database; RESEND_API_KEY?:string; NOTIFICATION_FROM_EMAIL?:string; [key:string]:unknown; }
type Row = Record<string,unknown>;
type Session={companyId:number;accountId:number;role:string;fullName:string;email:string;companyName:string;token:string};
const COOKIE="sas_contractor_v2",enc=new TextEncoder();
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const txt=(v:unknown,n=300)=>String(v??"").trim().slice(0,n);
const low=(v:unknown)=>txt(v).toLowerCase();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const fmt=(v:number,d=1)=>Number(v||0).toLocaleString("en-ZA",{maximumFractionDigits:d});
function cookie(req:Request){for(const p of (req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===COOKIE)return p.slice(i+1).trim()}return ""}
async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))),b=>b.toString(16).padStart(2,"0")).join("")}
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}
async function all(env:Env,sql:string,b:unknown[]=[]){try{return (await env.DB.prepare(sql).bind(...b).all<Row>()).results||[]}catch{return []}}
async function session(req:Request,env:Env):Promise<Session|null>{const token=cookie(req);if(!token)return null;const r=await first(env,`SELECT s.company_id companyId,s.account_id accountId,a.email,a.full_name fullName,COALESCE(NULLIF(s.active_role,''),a.role) role,c.name companyName FROM contractor_sessions s JOIN contractor_accounts a ON a.id=s.account_id JOIN companies c ON c.id=s.company_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND a.status='active' LIMIT 1`,[await hash(token)]);return r?{companyId:num(r.companyId),accountId:num(r.accountId),role:low(r.role),fullName:txt(r.fullName),email:txt(r.email),companyName:txt(r.companyName),token}:null}
function monthLabel(v:string){const [y,m]=v.split("-").map(Number);return new Date(Date.UTC(y,m-1,1)).toLocaleString("en-ZA",{month:"long",year:"numeric",timeZone:"UTC"})}
async function months(env:Env,s:Session){return all(env,`SELECT substr(period_start,1,7) month,MAX(id) batchId,MIN(period_start) periodStart,MAX(period_end) periodEnd,MAX(imported_at) importedAt,MAX(source_file) sourceFile FROM demo_import_batches_v1 WHERE company_id=? GROUP BY substr(period_start,1,7) ORDER BY month DESC`,[s.companyId])}
async function batchFor(env:Env,s:Session,month:string){return first(env,`SELECT id,period_start start,period_end end,source_file sourceFile,imported_at importedAt FROM demo_import_batches_v1 WHERE company_id=? AND substr(period_start,1,7)=? ORDER BY id DESC LIMIT 1`,[s.companyId,month])}
async function data(env:Env,s:Session,month:string){const batch=await batchFor(env,s,month);if(!batch)return {batch:null,rows:[],events:[],work:[],faults:[]};const id=num(batch.id),start=txt(batch.start),end=txt(batch.end);const rows=await all(env,"SELECT report_date date,fleet_number fleet,shift_hours shift,planned_downtime planned,unplanned_downtime unplanned,operating_hours operating,productive_hours productive,tonnes,fault_reason fault,severity,hour_meter hourMeter FROM demo_import_records_v1 WHERE batch_id=? AND company_id=? ORDER BY report_date,fleet_number",[id,s.companyId]);const events=await all(env,"SELECT fleet_number fleet,system_name system,description fault,severity,downtime_hours downtime,status,action,opened_at openedAt FROM events WHERE company_id=? AND event_type='historical_breakdown' AND date(opened_at)>=date(?) AND date(opened_at)<=date(?) ORDER BY opened_at DESC LIMIT 300",[s.companyId,start,end]);const work=await all(env,"SELECT fleet_number fleet,title,status,priority,assigned_to assignedTo,due_at dueAt FROM work_orders WHERE company_id=? AND (due_at IS NULL OR date(due_at)>=date(?) AND date(due_at)<=date(?)) ORDER BY id DESC LIMIT 150",[s.companyId,start,end]);const faults=await all(env,"SELECT fleet_number fleet,lower(trim(fault_reason)) fault,COUNT(*) count,SUM(unplanned_downtime) hours FROM demo_import_records_v1 WHERE batch_id=? AND company_id=? AND trim(COALESCE(fault_reason,''))<>'' GROUP BY fleet_number,lower(trim(fault_reason)) ORDER BY count DESC,hours DESC",[id,s.companyId]);return {batch,rows,events,work,faults}}
function metrics(rows:Row[]){const sum=(k:string)=>rows.reduce((a,r)=>a+num(r[k]),0),shift=sum("shift"),planned=sum("planned"),unplanned=sum("unplanned"),operating=sum("operating"),productive=sum("productive"),tonnes=sum("tonnes"),available=Math.max(0,shift-planned-unplanned);return {availability:shift?available/shift*100:0,utilisation:available?operating/available*100:0,tonnes,unplanned,operating,productive}}
function css(){return `<style>*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:#10223b;font-family:Arial,sans-serif}.histbar{background:#0d1b31;color:#fff;padding:14px 20px;display:flex;justify-content:space-between;gap:12px;align-items:center}.histbar a{color:#fff;text-decoration:none;font-weight:800}.wrap{max-width:1450px;margin:auto;padding:22px}.head{display:flex;justify-content:space-between;align-items:end;gap:14px;margin-bottom:16px}.head small{font-weight:900;color:#71809a;letter-spacing:.8px}.head h1{margin:5px 0 0}.months{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.month{display:block;background:#fff;border:1px solid #dde5ee;border-radius:13px;padding:18px;color:#10223b;text-decoration:none}.month:hover{border-color:#1c9b67;box-shadow:0 5px 18px rgba(15,35,55,.06)}.month b,.month span,.month small{display:block}.month b{font-size:20px;margin-bottom:8px}.month span{font-size:11px;color:#66768d}.month small{margin-top:10px;color:#8692a4}.badge{display:inline-block;background:#fff3c8;border:1px solid #dcb74b;border-radius:99px;padding:6px 10px;font-size:10px;font-weight:900}.back{display:inline-block;background:#14223a;color:#fff;text-decoration:none;padding:9px 12px;border-radius:8px;font-weight:900;font-size:11px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.kpi,.panel{background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:16px}.kpi small,.kpi b{display:block}.kpi small{font-size:9px;color:#6f7f97;font-weight:900}.kpi b{font-size:24px;margin-top:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.table{width:100%;border-collapse:collapse;font-size:11px}.table th{text-align:left;background:#f5f7fa;padding:8px}.table td{padding:8px;border-bottom:1px solid #e8edf3}.note{font-size:11px;color:#68778e;line-height:1.5}.emailbox{margin-top:14px;background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:16px}.emailbox label{display:block;padding:6px 0;font-size:11px}.btn{border:0;background:#14223a;color:#fff;padding:10px 13px;border-radius:8px;font-weight:900;cursor:pointer}.ok{padding:10px;background:#e8f7ef;color:#156a43;border-radius:8px;margin-bottom:12px}.err{padding:10px;background:#fff0f0;color:#a02323;border-radius:8px;margin-bottom:12px}@media(max-width:900px){.months,.kpis,.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.months,.kpis,.grid{grid-template-columns:1fr}.head,.histbar{display:block}}</style>`}
function table(heads:string[],rows:string[][]){return `<table class="table"><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join(""):`<tr><td colspan="${heads.length}">No historical records available.</td></tr>`}</tbody></table>`}
async function monthView(req:Request,env:Env,s:Session,month:string){const d=await data(env,s,month);if(!d.batch)return html(`<html><head>${css()}</head><body><div class="histbar"><a href="/contractor">← Dashboard</a><b>${esc(s.companyName)}</b></div><main class="wrap"><div class="err">That month is not available.</div><a class="back" href="/history">Back to Previous Months</a></main></body></html>`);const m=metrics(d.rows),period=`${txt(d.batch.start)} to ${txt(d.batch.end)}`,title=monthLabel(month),admin=["company_admin","admin"].includes(s.role),url=new URL(req.url),flash=txt(url.searchParams.get("msg"),500),tone=url.searchParams.get("tone")==="err"?"err":"ok";let body=`<div class="head"><div><small>PREVIOUS MONTHS · ${esc(s.role.toUpperCase())}</small><h1>${esc(title)}</h1><p class="note">${esc(period)} · Historical records are separate from current live operations.</p></div><div><span class="badge">HISTORICAL</span> <a class="back" href="/history">All months</a></div></div>${flash?`<div class="${tone}">${esc(flash)}</div>`:""}`;
 if(s.role==="mechanic"){const jobs=d.work.filter(x=>!x.assignedTo||low(x.assignedTo)===low(s.fullName)||low(x.assignedTo)===low(s.email)).slice(0,30),repeat=d.faults.filter(x=>num(x.count)>=2).slice(0,20);body+=`<div class="grid"><section class="panel"><h2>Machine breakdown history</h2>${table(["Fleet","Fault","Downtime","Action"],d.events.slice(0,40).map(e=>[esc(e.fleet),esc(e.fault),`${fmt(num(e.downtime))} h`,esc(e.action||"Recorded history")]))}</section><section class="panel"><h2>Repeat faults</h2>${table(["Fleet","Fault","Count"],repeat.map(x=>[esc(x.fleet),esc(x.fault),String(num(x.count))]))}<h2>Assigned / open work</h2>${table(["Fleet","Job","Status"],jobs.map(x=>[esc(x.fleet),esc(x.title),esc(x.status)]))}</section></div>`}
 else if(s.role==="supervisor"){body+=`<div class="kpis"><div class="kpi"><small>Availability</small><b>${m.availability.toFixed(1)}%</b></div><div class="kpi"><small>Utilisation</small><b>${m.utilisation.toFixed(1)}%</b></div><div class="kpi"><small>Unplanned downtime</small><b>${fmt(m.unplanned)} h</b></div><div class="kpi"><small>Work records</small><b>${d.work.length}</b></div></div><section class="panel"><h2>Shift / work-order history</h2>${table(["Fleet","Job","Status","Assigned"],d.work.slice(0,60).map(x=>[esc(x.fleet),esc(x.title),esc(x.status),esc(x.assignedTo||"Unassigned")]))}</section>`}
 else {body+=`<div class="kpis"><div class="kpi"><small>Availability</small><b>${m.availability.toFixed(1)}%</b></div><div class="kpi"><small>Utilisation</small><b>${m.utilisation.toFixed(1)}%</b></div><div class="kpi"><small>Production</small><b>${fmt(m.tonnes,0)} t</b></div><div class="kpi"><small>Unplanned downtime</small><b>${fmt(m.unplanned)} h</b></div></div><section class="panel"><h2>${s.role==="engineer"?"Engineering breakdown analysis":s.role==="manager"?"Management historical overview":"Company historical overview"}</h2>${table(["Fleet","System","Fault / reason","Severity","Downtime"],d.events.slice(0,80).map(e=>[esc(e.fleet),esc(e.system),esc(e.fault),esc(e.severity),`${fmt(num(e.downtime))} h`]))}</section>`}
 if(admin){const recipients=await all(env,"SELECT lower(email) email,full_name name,role FROM contractor_accounts WHERE company_id=? AND status='active' AND trim(email)<>'' UNION SELECT lower(email) email,name,'Alert contact' role FROM alert_contacts_v3 WHERE company_id=? AND active=1 AND trim(email)<>'' ORDER BY name",[s.companyId,s.companyId]);const csrf=await hash(s.token+"|history-email");body+=`<section class="emailbox"><h2>Admin controls for ${esc(title)}</h2><p class="note">Importing historical data never emails anyone automatically. Select exactly who should receive this month summary.</p><p><a class="back" href="/trial-demo">Import another previous month / ZIP</a></p><form method="post" action="/history/email"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="month" value="${esc(month)}">${recipients.map(r=>`<label><input type="checkbox" name="recipient" value="${esc(r.email)}"> <b>${esc(r.name)}</b> — ${esc(r.role)} · ${esc(r.email)}</label>`).join("")||'<p class="note">No active users or alert contacts are configured.</p>'}<button class="btn" type="submit">Send ${esc(title)} historical summary</button></form></section>`}
 return html(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} History · TMM Asset Health</title>${css()}</head><body><div class="histbar"><a href="/contractor">← Dashboard</a><b>${esc(s.companyName)} · ${esc(s.role)}</b></div><main class="wrap">${body}</main></body></html>`)}
async function historyIndex(req:Request,env:Env,s:Session){const ms=await months(env,s),url=new URL(req.url),flash=txt(url.searchParams.get("msg"),500);return html(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Previous Months · TMM Asset Health</title>${css()}</head><body><div class="histbar"><a href="/contractor">← Dashboard</a><b>${esc(s.companyName)} · ${esc(s.role)}</b></div><main class="wrap"><div class="head"><div><small>HISTORICAL INFORMATION</small><h1>Previous Months</h1><p class="note">Choose a month to open the historical dashboard for your current role.</p></div>${["company_admin","admin"].includes(s.role)?'<a class="back" href="/trial-demo">Import previous month / ZIP</a>':''}</div>${flash?`<div class="ok">${esc(flash)}</div>`:""}<div class="months">${ms.length?ms.map(r=>`<a class="month" href="/history?month=${esc(r.month)}"><b>${esc(monthLabel(txt(r.month)))}</b><span>${esc(r.periodStart)} to ${esc(r.periodEnd)}</span><small>Imported ${esc(String(r.importedAt).slice(0,16))}</small></a>`).join(""):'<section class="panel"><h2>No previous months yet</h2><p class="note">The Company Admin can import the first historical month from Previous Month Trial.</p></section>'}</div></main></body></html>`)}
async function sendHistoryEmail(req:Request,env:Env,s:Session){if(!["company_admin","admin"].includes(s.role))return redirect("/history","Company Administrator authority is required.","err");const f=await req.formData(),csrf=txt(f.get("csrf")),month=txt(f.get("month"),7);if(csrf!==await hash(s.token+"|history-email"))return redirect(`/history?month=${encodeURIComponent(month)}`,"Security check failed.","err");const d=await data(env,s,month);if(!d.batch)return redirect("/history","Historical month not found.","err");const allowed=new Set((await all(env,"SELECT lower(email) email FROM contractor_accounts WHERE company_id=? AND status='active' UNION SELECT lower(email) email FROM alert_contacts_v3 WHERE company_id=? AND active=1",[s.companyId,s.companyId])).map(x=>low(x.email)).filter(x=>x.includes("@")));const recipients=[...new Set(f.getAll("recipient").map(String).map(low))].filter(x=>allowed.has(x)).slice(0,10);if(!recipients.length)return redirect(`/history?month=${encodeURIComponent(month)}`,"Select at least one valid recipient.","err");if(!env.RESEND_API_KEY)return redirect(`/history?month=${encodeURIComponent(month)}`,"Email service is not configured.","err");const m=metrics(d.rows),subject=`${monthLabel(month)} historical summary · ${s.companyName}`,htmlBody=`<div style="font-family:Arial,sans-serif;max-width:720px;margin:auto"><div style="background:#0d1b31;color:#fff;padding:20px"><h2 style="margin:0">TMM Asset Health · Historical Summary</h2><p>${esc(s.companyName)} · ${esc(monthLabel(month))}</p></div><div style="padding:20px;border:1px solid #dfe6ef"><p><b>Historical information only — not a current live incident.</b></p><p>Availability: <b>${m.availability.toFixed(1)}%</b><br>Utilisation: <b>${m.utilisation.toFixed(1)}%</b><br>Production: <b>${fmt(m.tonnes,0)} t</b><br>Unplanned downtime: <b>${fmt(m.unplanned)} h</b></p><p>Recorded breakdowns: <b>${d.events.length}</b></p></div></div>`;const res=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:txt(env.NOTIFICATION_FROM_EMAIL||"TMM Asset Health <notifications@sindaneassetsolutions.co.za>",250),to:recipients,subject,html:htmlBody,reply_to:"admin@sindaneassetsolutions.co.za"})});if(!res.ok){const e=await res.json().catch(()=>({})) as Row;return redirect(`/history?month=${encodeURIComponent(month)}`,`Email failed: ${txt(e.message||res.status,300)}`,"err")}return redirect(`/history?month=${encodeURIComponent(month)}`,`${monthLabel(month)} summary sent to ${recipients.length} selected recipient(s).`)}
function redirect(base:string,msg:string,tone="ok"){const u=new URL(base,"https://local.invalid");u.searchParams.set("msg",msg);if(tone==="err")u.searchParams.set("tone","err");return new Response(null,{status:303,headers:{location:u.pathname+u.search,"cache-control":"no-store"}})}
function html(body:string,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
function injectHistoryNav(body:string){if(body.includes('href="/history"')||!body.includes("</nav>"))return body;const link=`<a href="/history"><span>◷</span>Previous Months</a>`;return body.replace("</nav>",`${link}</nav>`)}
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url),s=await session(req,env);if(s&&req.method==="GET"&&url.pathname==="/history"){const month=txt(url.searchParams.get("month"),7);return month?monthView(req,env,s,month):historyIndex(req,env,s)}if(s&&req.method==="POST"&&url.pathname==="/history/email")return sendHistoryEmail(req,env,s);const res=await currentApp.fetch(req,env as never,ctx as never);if(!s||req.method!=="GET"||url.pathname!=="/contractor")return res;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let body=injectHistoryNav(await res.text());const h=new Headers(res.headers);h.set("cache-control","private, no-store");h.delete("content-length");return new Response(body,{status:res.status,headers:h})},async scheduled(controller:ScheduledController,env:Env,ctx:ExecutionContext){const app=currentApp as unknown as {scheduled?:(c:ScheduledController,e:Env,x:ExecutionContext)=>Promise<void>|void};if(app.scheduled)return app.scheduled(controller,env,ctx)}};