import currentApp from "./router-reliability-workflow";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime:number; cron:string; noRetry():void; }
interface Env { DB:D1Database; RESEND_API_KEY?:string; ALERT_FROM_EMAIL?:string; [key:string]:unknown; }
type Row=Record<string,unknown>;

const txt=(v:unknown,n=500)=>String(v??"").trim().slice(0,n);
const low=(v:unknown)=>txt(v).toLowerCase();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
async function all(env:Env,sql:string,b:unknown[]=[]){try{return (await env.DB.prepare(sql).bind(...b).all<Row>()).results||[]}catch{return []}}
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}

async function ensure(env:Env){for(const q of [
`CREATE TABLE IF NOT EXISTS telemetry_email_log_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,alert_id INTEGER NOT NULL,recipient TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',provider_message_id TEXT,error_text TEXT,attempts INTEGER NOT NULL DEFAULT 0,last_attempt_at TEXT,created_at TEXT NOT NULL,UNIQUE(alert_id,recipient))`,
`CREATE INDEX IF NOT EXISTS idx_telemetry_email_log_alert ON telemetry_email_log_v1(company_id,alert_id,status)`,
`CREATE INDEX IF NOT EXISTS idx_telemetry_email_log_status ON telemetry_email_log_v1(status,last_attempt_at)`])await env.DB.prepare(q).run()}

function validEmail(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}

async function recipients(env:Env,alert:Row){const companyId=num(alert.company_id),severity=low(alert.severity);const out=new Set<string>();
 const contacts=await all(env,`SELECT email,breakdown,critical,active FROM alert_contacts_v3 WHERE company_id=? AND active=1 AND email IS NOT NULL AND trim(email)<>''`,[companyId]);
 for(const c of contacts){const email=low(c.email);if(!validEmail(email))continue;const wantsCritical=num(c.critical)===1,wantsBreakdown=num(c.breakdown)===1;if(severity==="critical"?wantsCritical:(wantsBreakdown||wantsCritical))out.add(email)}
 const settings=await first(env,"SELECT contact_email email FROM company_settings_v3 WHERE company_id=?",[companyId]);const fallback=low(settings?.email);if(validEmail(fallback))out.add(fallback);
 return [...out].slice(0,20)
}

function subject(alert:Row){return `[${txt(alert.severity,20).toUpperCase()}] ${txt(alert.machine_id,80)} · ${txt(alert.title,160)}`}
function emailHtml(alert:Row,companyName:string){const sev=txt(alert.severity,20).toUpperCase(),machine=txt(alert.machine_id,100),title=txt(alert.title,180),details=txt(alert.details,1200),time=txt(alert.created_at,50).replace("T"," ").slice(0,19);return `<!doctype html><html><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#10203a"><div style="max-width:680px;margin:24px auto;background:#fff;border:1px solid #dce4ef;border-radius:12px;overflow:hidden"><div style="background:#0d1b31;color:#fff;padding:20px"><b style="font-size:20px">TMM Asset Health</b><div style="font-size:12px;margin-top:5px">${esc(companyName)} · Automatic machine condition alert</div></div><div style="padding:22px"><div style="display:inline-block;padding:6px 10px;border-radius:999px;background:#fff1e8;color:#9b3d00;font-weight:800;font-size:12px">${esc(sev)}</div><h2 style="margin:14px 0 6px">${esc(title)}</h2><p style="margin:0 0 14px"><b>Machine:</b> ${esc(machine)}</p><div style="background:#f6f8fb;border-radius:9px;padding:14px;line-height:1.5">${esc(details)}</div><p style="font-size:12px;color:#667085;margin-top:16px"><b>Detected:</b> ${esc(time||"Now")}</p><p style="font-size:12px;color:#667085">This is an automated condition indication from TMM Asset Health. Confirm the condition on the machine before maintenance action.</p><a href="https://tmm-asset-health.mandlenkosisindane43.workers.dev/condition-monitoring" style="display:inline-block;background:#0a7a49;color:#fff;text-decoration:none;padding:11px 15px;border-radius:8px;font-weight:800">Open Condition Monitoring</a></div></div></body></html>`}

async function sendOne(env:Env,alert:Row,email:string,companyName:string){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO telemetry_email_log_v1(company_id,alert_id,recipient,status,attempts,last_attempt_at,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(alert_id,recipient) DO UPDATE SET attempts=telemetry_email_log_v1.attempts+1,last_attempt_at=excluded.last_attempt_at`).bind(num(alert.company_id),num(alert.id),email,"pending",1,now,now).run();
 if(!env.RESEND_API_KEY){await env.DB.prepare("UPDATE telemetry_email_log_v1 SET status='waiting_configuration',error_text=? WHERE alert_id=? AND recipient=?").bind("RESEND_API_KEY is not configured",num(alert.id),email).run();return}
 try{const res=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:txt(env.ALERT_FROM_EMAIL||"TMM Asset Health <admin@sindaneassetsolutions.co.za>",200),to:[email],subject:subject(alert),html:emailHtml(alert,companyName)})});const data=await res.json().catch(()=>({})) as Row;if(!res.ok)throw new Error(txt(data.message||data.name||`HTTP ${res.status}`,500));await env.DB.prepare("UPDATE telemetry_email_log_v1 SET status='sent',provider_message_id=?,error_text=NULL,last_attempt_at=? WHERE alert_id=? AND recipient=?").bind(txt(data.id,200),now,num(alert.id),email).run()}catch(e){await env.DB.prepare("UPDATE telemetry_email_log_v1 SET status='failed',error_text=?,last_attempt_at=? WHERE alert_id=? AND recipient=?").bind(e instanceof Error?e.message:String(e),now,num(alert.id),email).run()}}

async function dispatch(env:Env){await ensure(env);const alerts=await all(env,`SELECT a.*,c.name company_name FROM telemetry_alerts_v1 a JOIN companies c ON c.id=a.company_id WHERE a.status!='closed' AND lower(a.severity) IN ('high','critical') AND datetime(a.created_at)>datetime('now','-7 days') ORDER BY a.id DESC LIMIT 50`);for(const a of alerts){const recips=await recipients(env,a);for(const email of recips){const log=await first(env,"SELECT status,attempts,last_attempt_at FROM telemetry_email_log_v1 WHERE alert_id=? AND recipient=?",[num(a.id),email]);if(log&&low(log.status)==="sent")continue;if(log&&num(log.attempts)>=5)continue;if(log&&log.last_attempt_at&&Date.now()-new Date(txt(log.last_attempt_at,60)).getTime()<5*60*1000)continue;await sendOne(env,a,email,txt(a.company_name,160))}}}

async function statusPage(env:Env){await ensure(env);const rows=await all(env,`SELECT l.*,a.machine_id,a.title,a.severity,c.name company_name FROM telemetry_email_log_v1 l JOIN telemetry_alerts_v1 a ON a.id=l.alert_id JOIN companies c ON c.id=l.company_id ORDER BY l.id DESC LIMIT 100`);const sent=rows.filter(r=>low(r.status)==="sent").length,failed=rows.filter(r=>["failed","waiting_configuration"].includes(low(r.status))).length;const tr=rows.map(r=>`<tr><td>${esc(r.company_name)}</td><td><b>${esc(r.machine_id)}</b></td><td>${esc(r.severity)}</td><td>${esc(r.recipient)}</td><td>${esc(r.status)}</td><td>${esc(r.error_text||"—")}</td><td>${esc(String(r.last_attempt_at||"").slice(0,19).replace("T"," "))}</td></tr>`).join("");return new Response(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Automatic Alert Email</title><style>body{font-family:Arial;background:#f4f7fb;color:#10203a;margin:0}.wrap{max-width:1400px;margin:auto;padding:24px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card,.panel{background:white;border:1px solid #dce4ef;border-radius:12px;padding:16px;margin-bottom:12px}.card b{display:block;font-size:26px;margin-top:5px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:9px;border-top:1px solid #e7edf4;text-align:left}th{background:#f3f6f9}.ok{color:#087548}.warn{color:#a35f00}</style></head><body><main class="wrap"><p><a href="/condition-monitoring">← Condition Monitoring</a></p><h1>Automatic alert email</h1><p>High and critical telemetry conditions are automatically queued to configured company alert contacts. Email delivery uses Resend.</p><div class="cards"><div class="card"><small>EMAIL SERVICE</small><b class="${env.RESEND_API_KEY?"ok":"warn"}">${env.RESEND_API_KEY?"Configured":"Needs key"}</b></div><div class="card"><small>SENT LOGS</small><b>${sent}</b></div><div class="card"><small>FAILED / WAITING</small><b>${failed}</b></div></div><section class="panel"><table><tr><th>Company</th><th>Machine</th><th>Severity</th><th>Recipient</th><th>Status</th><th>Detail</th><th>Last attempt</th></tr>${tr||`<tr><td colspan="7">No automatic alert emails have been queued yet.</td></tr>`}</table></section></main></body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}

export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url);if(url.pathname==="/automatic-alert-email"&&req.method==="GET"){ctx.waitUntil(dispatch(env));return statusPage(env)}const res=await currentApp.fetch(req,env as never,ctx as never);ctx.waitUntil(dispatch(env));return res},async scheduled(c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(dispatch(env));const app=currentApp as unknown as {scheduled?:(c:ScheduledController,e:Env,x:ExecutionContext)=>Promise<void>|void};if(app.scheduled)return app.scheduled(c,env,ctx)}};
