import currentApp from "./router-trial-zip-package";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime:number; cron:string; noRetry():void; }
interface Env { DB:D1Database; [key:string]:unknown; }
type Row = Record<string,unknown>;
type Session={companyId:number;accountId:number;role:string;fullName:string;email:string;companyName:string;token:string};
const COOKIE="sas_contractor_v2",enc=new TextEncoder();
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const txt=(v:unknown,n=300)=>String(v??"").trim().slice(0,n);
const low=(v:unknown)=>txt(v).toLowerCase();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const fmt=(v:number,d=1)=>Number(v||0).toLocaleString("en-ZA",{maximumFractionDigits:d});
function cookie(req:Request){for(const p of (req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===COOKIE)return p.slice(i+1).trim()}return ""}
async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))),b=>b.toString(16).padStart(2,"0")).join("")}
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}
async function all(env:Env,sql:string,b:unknown[]=[]){try{return (await env.DB.prepare(sql).bind(...b).all<Row>()).results||[]}catch{return []}}
async function session(req:Request,env:Env):Promise<Session|null>{const token=cookie(req);if(!token)return null;const r=await first(env,`SELECT s.company_id companyId,s.account_id accountId,a.email,a.full_name fullName,COALESCE(NULLIF(s.active_role,''),a.role) role,c.name companyName FROM contractor_sessions s JOIN contractor_accounts a ON a.id=s.account_id JOIN companies c ON c.id=s.company_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND a.status='active' LIMIT 1`,[await hash(token)]);return r?{companyId:num(r.companyId),accountId:num(r.accountId),role:low(r.role),fullName:txt(r.fullName),email:txt(r.email),companyName:txt(r.companyName),token}:null}
async function latestBatch(env:Env,s:Session){return first(env,"SELECT id,period_start start,period_end end,source_file sourceFile,imported_at importedAt FROM demo_import_batches_v1 WHERE company_id=? ORDER BY id DESC LIMIT 1",[s.companyId])}
async function historyData(env:Env,s:Session){const batch=await latestBatch(env,s);if(!batch)return {batch:null,rows:[],events:[],work:[],machines:[],faults:[]};const id=num(batch.id);const rows=await all(env,"SELECT report_date date,fleet_number fleet,shift_hours shift,planned_downtime planned,unplanned_downtime unplanned,operating_hours operating,productive_hours productive,tonnes,fault_reason fault,severity,hour_meter hourMeter FROM demo_import_records_v1 WHERE batch_id=? AND company_id=? ORDER BY report_date,fleet_number",[id,s.companyId]);const events=await all(env,"SELECT fleet_number fleet,system_name system,description fault,severity,downtime_hours downtime,status,action,opened_at openedAt FROM events WHERE company_id=? AND event_type='historical_breakdown' AND action='Historical trial import — no live notification' ORDER BY opened_at DESC LIMIT 150",[s.companyId]);const work=await all(env,"SELECT fleet_number fleet,title,status,priority,assigned_to assignedTo,due_at dueAt FROM work_orders WHERE company_id=? ORDER BY id DESC LIMIT 100",[s.companyId]);const machines=await all(env,"SELECT fleet_number fleet,category,site,operating_hours hours,next_service_hours nextService,status FROM machines WHERE company_id=? ORDER BY fleet_number",[s.companyId]);const faults=await all(env,"SELECT fleet_number fleet,lower(trim(fault_reason)) fault,COUNT(*) count,SUM(unplanned_downtime) hours FROM demo_import_records_v1 WHERE batch_id=? AND company_id=? AND trim(COALESCE(fault_reason,''))<>'' GROUP BY fleet_number,lower(trim(fault_reason)) ORDER BY count DESC,hours DESC",[id,s.companyId]);return {batch,rows,events,work,machines,faults}}
function metrics(rows:Row[]){const sum=(k:string)=>rows.reduce((a,r)=>a+num(r[k]),0),shift=sum("shift"),planned=sum("planned"),unplanned=sum("unplanned"),operating=sum("operating"),productive=sum("productive"),tonnes=sum("tonnes"),available=Math.max(0,shift-planned-unplanned);return {availability:shift?available/shift*100:0,utilisation:available?operating/available*100:0,tonnes,unplanned,operating,productive}}
function css(){return `<style>.hist-wrap{margin:18px 20px 28px;padding:18px;background:#fff;border:1px solid #dce5ee;border-radius:14px;color:#10223b;font-family:Arial,sans-serif}.hist-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:14px}.hist-head h2{margin:2px 0;font-size:20px}.hist-head small{font-weight:900;color:#72809a;letter-spacing:.7px}.hist-badge{background:#fff4cf;border:1px solid #e4bd4f;border-radius:999px;padding:6px 10px;font-size:10px;font-weight:900}.hist-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.hist-kpi{background:#f7f9fc;border:1px solid #e3e8f0;border-radius:10px;padding:12px}.hist-kpi small,.hist-kpi b{display:block}.hist-kpi small{font-size:9px;color:#708099;font-weight:900}.hist-kpi b{font-size:22px;margin-top:7px}.hist-table{width:100%;border-collapse:collapse;font-size:11px;margin-top:10px}.hist-table th{text-align:left;background:#f4f7fb;padding:8px}.hist-table td{padding:8px;border-bottom:1px solid #e8edf3}.hist-btn{display:inline-block;background:#14223a;color:#fff!important;text-decoration:none;padding:9px 12px;border-radius:8px;font-weight:900;font-size:11px}.hist-note{font-size:11px;color:#68778e;line-height:1.5}.hist-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:850px){.hist-kpis,.hist-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.hist-kpis,.hist-grid{grid-template-columns:1fr}.hist-head{display:block}}</style>`}
function table(heads:string[],rows:string[][]){return `<table class="hist-table"><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join(""):`<tr><td colspan="${heads.length}">No historical records available.</td></tr>`}</tbody></table>`}
async function panel(env:Env,s:Session){const d=await historyData(env,s);if(!d.batch)return `${css()}<section class="hist-wrap"><div class="hist-head"><div><small>PREVIOUS MONTH HISTORY</small><h2>No historical import yet</h2></div></div><p class="hist-note">The Company Admin can import the previous calendar month from Previous Month Trial.</p></section>`;const m=metrics(d.rows),period=`${txt(d.batch.start)} to ${txt(d.batch.end)}`;
 if(s.role==="mechanic"){const relevantEvents=d.events.slice(0,12),repeat=d.faults.filter(x=>num(x.count)>=2).slice(0,8),jobs=d.work.filter(x=>!x.assignedTo||low(x.assignedTo)===low(s.fullName)||low(x.assignedTo)===low(s.email)).slice(0,10);return `${css()}<section class="hist-wrap"><div class="hist-head"><div><small>PREVIOUS MONTH MACHINE HISTORY</small><h2>Breakdowns, repeat faults and assigned work</h2><p class="hist-note">${esc(period)} · Historical records only. They do not replace today's live work queue.</p></div><span class="hist-badge">HISTORICAL</span></div><div class="hist-grid"><div><h3>Previous breakdowns</h3>${table(["Fleet","Fault","Downtime","Action"],relevantEvents.map(e=>[esc(e.fleet),esc(e.fault),`${fmt(num(e.downtime))} h`,esc(e.action||"Recorded history")]))}</div><div><h3>Repeat faults</h3>${table(["Fleet","Fault","Count"],repeat.map(x=>[esc(x.fleet),esc(x.fault),String(num(x.count))]))}<h3>Assigned / open work</h3>${table(["Fleet","Job","Status"],jobs.map(x=>[esc(x.fleet),esc(x.title),esc(x.status)]))}</div></div></section>`}
 const full=["engineer","manager"].includes(s.role);if(full)return `${css()}<section class="hist-wrap"><div class="hist-head"><div><small>PREVIOUS MONTH HISTORICAL DASHBOARD</small><h2>${esc(s.role==="manager"?"Management performance":"Engineering performance")}</h2><p class="hist-note">${esc(period)} · Imported historical data kept separate from current live operations.</p></div><div><span class="hist-badge">HISTORICAL</span> <a class="hist-btn" href="/trial-demo">Open full previous-month analysis</a></div></div><div class="hist-kpis"><div class="hist-kpi"><small>Availability</small><b>${m.availability.toFixed(1)}%</b></div><div class="hist-kpi"><small>Utilisation</small><b>${m.utilisation.toFixed(1)}%</b></div><div class="hist-kpi"><small>Production</small><b>${fmt(m.tonnes,0)} t</b></div><div class="hist-kpi"><small>Unplanned downtime</small><b>${fmt(m.unplanned)} h</b></div></div>${table(["Fleet","Fault / reason","Severity","Downtime"],d.events.slice(0,15).map(e=>[esc(e.fleet),esc(e.fault),esc(e.severity),`${fmt(num(e.downtime))} h`]))}</section>`;
 return `${css()}<section class="hist-wrap"><div class="hist-head"><div><small>PREVIOUS MONTH OPERATIONS</small><h2>Historical shift and maintenance context</h2><p class="hist-note">${esc(period)}</p></div><span class="hist-badge">HISTORICAL</span></div>${table(["Fleet","Job","Status","Assigned"],d.work.slice(0,12).map(x=>[esc(x.fleet),esc(x.title),esc(x.status),esc(x.assignedTo||"Unassigned")]))}</section>`}
function html(body:string,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
async function historyPage(env:Env,s:Session){const p=await panel(env,s);return html(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Previous Month History · TMM Asset Health</title><style>body{margin:0;background:#f3f6fa}.bar{background:#0d1b31;color:white;padding:14px 20px;font-family:Arial,sans-serif}.bar a{color:white;margin-right:18px;text-decoration:none;font-weight:800}</style></head><body><div class="bar"><a href="/contractor">← Dashboard</a><b>${esc(s.companyName)} · ${esc(s.role)}</b></div>${p}</body></html>`)}
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url),s=await session(req,env);if(s&&url.pathname==="/trial-demo"&&s.role==="mechanic")return new Response(null,{status:303,headers:{location:"/history"}});if(s&&url.pathname==="/history"&&req.method==="GET"){if(["company_admin","admin"].includes(s.role))return new Response(null,{status:303,headers:{location:"/trial-demo"}});return historyPage(env,s)}const res=await currentApp.fetch(req,env as never,ctx as never);if(!s||req.method!=="GET"||url.pathname!=="/contractor"||["company_admin","admin"].includes(s.role))return res;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let body=await res.text();const p=await panel(env,s);const link=`<div style="margin:0 20px 10px"><a href="/history" style="display:inline-block;background:#14223a;color:#fff;text-decoration:none;padding:9px 12px;border-radius:8px;font:800 11px Arial">Open Previous Month History</a></div>`;if(body.includes("</main>"))body=body.replace("</main>",`${p}${link}</main>`);else if(body.includes("</body>"))body=body.replace("</body>",`${p}${link}</body>`);const h=new Headers(res.headers);h.set("cache-control","private, no-store");h.delete("content-length");return new Response(body,{status:res.status,headers:h})},async scheduled(controller:ScheduledController,env:Env,ctx:ExecutionContext){const app=currentApp as unknown as {scheduled?:(c:ScheduledController,e:Env,x:ExecutionContext)=>Promise<void>|void};if(app.scheduled)return app.scheduled(controller,env,ctx)}};