import currentApp from "./router-owner-licence-ui";
import * as XLSX from "xlsx";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime: number; cron: string; noRetry(): void; }
interface Env { DB: D1Database; BUCKET?: R2Bucket; [key: string]: unknown; }
type Row = Record<string, unknown>;
type Session = { companyId:number; accountId:number; role:string; token:string; companyName:string };
type DemoRow={date:string;site:string;fleet:string;shift:number;planned:number;unplanned:number;operating:number;productive:number;tonnes:number;fault:string;severity:string;hourMeter:number|null};

const COOKIE="sas_contractor_v2";
const enc=new TextEncoder();
function txt(v:unknown,n=300){return String(v??"").trim().slice(0,n)}
function lower(v:unknown){return txt(v).toLowerCase()}
function num(v:unknown,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
function clamp(v:number,min=0,max=1e9){return Math.max(min,Math.min(max,v))}
function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c))}
function cookie(req:Request,name:string){for(const p of (req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===name)return p.slice(i+1).trim()}return ""}
async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))),b=>b.toString(16).padStart(2,"0")).join("")}
async function first(env:Env,sql:string,binds:unknown[]=[]){return env.DB.prepare(sql).bind(...binds).first<Row>()}
async function all(env:Env,sql:string,binds:unknown[]=[]){return (await env.DB.prepare(sql).bind(...binds).all<Row>()).results||[]}
async function session(req:Request,env:Env):Promise<Session|null>{const token=cookie(req,COOKIE);if(!token)return null;const r=await first(env,`SELECT s.company_id companyId,s.account_id accountId,COALESCE(NULLIF(s.active_role,''),a.role) role,c.name companyName FROM contractor_sessions s JOIN contractor_accounts a ON a.id=s.account_id JOIN companies c ON c.id=s.company_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND a.status='active' LIMIT 1`,[await hash(token)]).catch(()=>null);return r?{companyId:num(r.companyId),accountId:num(r.accountId),role:lower(r.role),token,companyName:txt(r.companyName)}:null}
function redirect(msg:string,tone="ok"){return new Response(null,{status:303,headers:{location:`/trial-demo?msg=${encodeURIComponent(msg)}&tone=${tone}`,"cache-control":"no-store"}})}

async function ensure(env:Env){
  const q=[
    `CREATE TABLE IF NOT EXISTS demo_zip_packages_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,package_name TEXT NOT NULL,object_key TEXT,imported_by INTEGER NOT NULL,imported_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS demo_zip_sections_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,package_id INTEGER NOT NULL,company_id INTEGER NOT NULL,section_key TEXT NOT NULL,file_name TEXT NOT NULL,row_count INTEGER NOT NULL,data_json TEXT NOT NULL,created_at TEXT NOT NULL)`,
    `CREATE INDEX IF NOT EXISTS idx_demo_zip_company ON demo_zip_packages_v1(company_id,id)`,
    `CREATE INDEX IF NOT EXISTS idx_demo_zip_sections ON demo_zip_sections_v1(company_id,package_id,section_key)`,
    `CREATE TABLE IF NOT EXISTS demo_import_batches_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,source_file TEXT NOT NULL,object_key TEXT,period_start TEXT NOT NULL,period_end TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'complete',total_rows INTEGER NOT NULL,matched_rows INTEGER NOT NULL,unmatched_rows INTEGER NOT NULL,outside_rows INTEGER NOT NULL DEFAULT 0,imported_by INTEGER NOT NULL,imported_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS demo_import_records_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,batch_id INTEGER NOT NULL,company_id INTEGER NOT NULL,report_date TEXT NOT NULL,site TEXT NOT NULL,fleet_number TEXT NOT NULL,shift_hours REAL NOT NULL,planned_downtime REAL NOT NULL,unplanned_downtime REAL NOT NULL,operating_hours REAL NOT NULL,productive_hours REAL NOT NULL,tonnes REAL NOT NULL,fault_reason TEXT,severity TEXT NOT NULL,hour_meter REAL,created_at TEXT NOT NULL)`,
    `CREATE INDEX IF NOT EXISTS idx_demo_records_company_batch ON demo_import_records_v1(company_id,batch_id,report_date)`
  ];
  await env.DB.batch(q.map(x=>env.DB.prepare(x)));
}
function u16(v:DataView,o:number){return v.getUint16(o,true)}
function u32(v:DataView,o:number){return v.getUint32(o,true)}
async function unzip(bytes:Uint8Array){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(u32(view,i)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error("Invalid ZIP file: end record not found.");const total=u16(view,eocd+10),central=u32(view,eocd+16);let p=central;const out:{name:string;bytes:Uint8Array}[]=[];for(let i=0;i<total;i++){if(u32(view,p)!==0x02014b50)throw new Error("Invalid ZIP directory.");const method=u16(view,p+10),compSize=u32(view,p+20),nameLen=u16(view,p+28),extraLen=u16(view,p+30),commentLen=u16(view,p+32),localOff=u32(view,p+42);const name=new TextDecoder().decode(bytes.slice(p+46,p+46+nameLen));p+=46+nameLen+extraLen+commentLen;if(name.endsWith("/"))continue;if(u32(view,localOff)!==0x04034b50)throw new Error(`Invalid ZIP entry: ${name}`);const localName=u16(view,localOff+26),localExtra=u16(view,localOff+28),start=localOff+30+localName+localExtra,compressed=bytes.slice(start,start+compSize);let data:Uint8Array;if(method===0)data=compressed;else if(method===8){const ds=new DecompressionStream("deflate-raw" as CompressionFormat);const ab=await new Response(new Blob([compressed]).stream().pipeThrough(ds)).arrayBuffer();data=new Uint8Array(ab)}else throw new Error(`ZIP compression method ${method} is not supported (${name}).`);out.push({name,bytes:data})}return out}
function csvLine(line:string){const out:string[]=[];let cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===","&&!q){out.push(cur.trim());cur=""}else cur+=c}out.push(cur.trim());return out}
function parseCsv(bytes:Uint8Array){const lines=new TextDecoder().decode(bytes).split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return [] as Row[];const h=csvLine(lines[0]);return lines.slice(1).map(line=>{const vals=csvLine(line),r:Row={};h.forEach((k,i)=>r[k]=vals[i]??"");return r})}
function parseExcel(name:string,bytes:Uint8Array){const wb=XLSX.read(bytes,{type:"array",cellDates:false});return wb.SheetNames.map(sheetName=>({name:`${name}/${sheetName}`,key:sectionKey(`${name} ${sheetName}`),rows:XLSX.utils.sheet_to_json<Row>(wb.Sheets[sheetName],{defval:""})}))}
function normal(r:Row){const n:Row={};for(const[k,v]of Object.entries(r))n[k.toLowerCase().replace(/[^a-z0-9]/g,"")]=v;return n}
function sectionKey(name:string){const n=name.toLowerCase();if(n.includes("monthly_summary"))return "summary";if(n.includes("fleet_register"))return "fleet";if(n.includes("daily_production")||n.includes("daily_report"))return "production";if(n.includes("telemetry_alert"))return "telemetry_alerts";if(n.includes("telemat"))return "telemetry";if(n.includes("breakdown"))return "breakdowns";if(n.includes("maintenance"))return "maintenance";if(n.includes("job_card"))return "job_cards";if(n.includes("work_order"))return "work_orders";if(n.includes("purchase_order"))return "purchase_orders";if(n.includes("quotation"))return "quotations";if(n.includes("payment"))return "payments";if(n.includes("spares"))return "spares";if(n.includes("approval"))return "approvals";if(n.includes("users_roles")||n.includes("user_role"))return "users_roles";if(n.includes("document"))return "documents";if(n.includes("expected_result"))return "expected_results";return "other"}
function previousMonth(){const d=new Date();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-1);const start=d.toISOString().slice(0,7)+"-01";d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);return{start,end:d.toISOString().slice(0,10),label:d.toLocaleString("en-ZA",{month:"long",year:"numeric",timeZone:"UTC"})}}
function dateValue(v:unknown){const s=txt(v,30);const iso=s.match(/^(\d{4})[-\/]([01]?\d)[-\/]([0-3]?\d)/);if(iso)return`${iso[1]}-${iso[2].padStart(2,"0")}-${iso[3].padStart(2,"0")}`;const za=s.match(/^([0-3]?\d)[-\/]([01]?\d)[-\/](\d{4})/);return za?`${za[3]}-${za[2].padStart(2,"0")}-${za[1].padStart(2,"0")}`:""}
function parseProduction(raw:Row,defaultShift:number):DemoRow|null{const n=normal(raw),fleet=txt(n.fleetnumber||n.fleet||n.machineid||n.machine||n.equipment,120),date=dateValue(n.reportdate||n.date||n.day);if(!fleet||!date)return null;const shift=clamp(num(n.shifthours??n.plannedhours??n.scheduledhours,defaultShift),0,48),planned=clamp(num(n.planneddowntime??n.planneddowntimehours),0,shift),unplanned=clamp(num(n.unplanneddowntime??n.breakdownhours??n.downtimehours??n.downtime),0,shift-planned),operating=clamp(num(n.operatinghours??n.runtime??n.workinghours,Math.max(0,shift-planned-unplanned)),0,shift),productive=clamp(num(n.productivehours??n.utilisedhours??n.utilizedhours,operating),0,operating),hm=(n.hourmeter==null&&n.currenthours==null)?null:num(n.hourmeter??n.currenthours);return{date,site:txt(n.site||"Main Site",120),fleet,shift,planned,unplanned,operating,productive,tonnes:clamp(num(n.tonnes??n.tonnage??n.production)),fault:txt(n.faultreason||n.faultcause||n.downtimereason||n.fault||n.cause,500),severity:["low","medium","high","critical"].includes(lower(n.severity))?lower(n.severity):unplanned>=8?"critical":unplanned>=4?"high":"medium",hourMeter:hm}}
async function batchRun(env:Env,stmts:D1PreparedStatement[],size=100){for(let i=0;i<stmts.length;i+=size)await env.DB.batch(stmts.slice(i,i+size))}

async function importFleet(env:Env,s:Session,rows:Row[]){const existing=await all(env,"SELECT id,fleet_number fleet FROM machines WHERE company_id=?",[s.companyId]);const map=new Map(existing.map(x=>[lower(x.fleet),num(x.id)]));const stmts:D1PreparedStatement[]=[];let created=0,updated=0;const now=new Date().toISOString();for(const raw of rows){const n=normal(raw),fleet=txt(n.machineid||n.fleetnumber||n.machine||n.fleet,120);if(!fleet)continue;const category=txt(n.machinetype||n.type||n.category||"Machine",120),site=txt(n.sitearea||n.site||"Main Site",120);let status=lower(n.status||"operating");if(status==="active")status="operating";const hours=num(n.openinghourmeter??n.hourmeter??n.operatinghours),nextRaw=n.nextservicehour??n.nextservicehours,next=String(nextRaw??"").trim()===""?null:num(nextRaw),id=map.get(lower(fleet));if(id){stmts.push(env.DB.prepare("UPDATE machines SET fleet_number=?,category=?,site=?,status=?,operating_hours=?,next_service_hours=? WHERE id=? AND company_id=?").bind(fleet,category,site,status,hours,next,id,s.companyId));updated++}else{stmts.push(env.DB.prepare("INSERT INTO machines(company_id,fleet_number,category,site,status,operating_hours,availability_target,next_service_hours,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(s.companyId,fleet,category,site,status,hours,0.9,next,now));created++}}
  if(stmts.length)await batchRun(env,stmts);return{created,updated};
}

async function importLiveSections(env:Env,s:Session,sections:{name:string;key:string;rows:Row[]}[],sourceName:string){
  const now=new Date().toISOString(),source=`zip-test:${sourceName}`,marker="[TEST ZIP]";
  for(const q of [
    `CREATE TABLE IF NOT EXISTS machine_telemetry_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,machine_id TEXT NOT NULL,recorded_at TEXT NOT NULL,engine_hours REAL,ignition_status TEXT,latitude REAL,longitude REAL,fuel_level REAL,odometer REAL,hydraulic_pressure REAL,hydraulic_oil_level REAL,engine_oil_pressure REAL,coolant_temperature REAL,rpm REAL,engine_load REAL,fault_code TEXT,source TEXT NOT NULL DEFAULT 'api',raw_json TEXT,created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS telemetry_alerts_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,machine_id TEXT NOT NULL,telemetry_id INTEGER NOT NULL,alert_type TEXT NOT NULL,severity TEXT NOT NULL,title TEXT NOT NULL,details TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS mechanic_job_evidence_v1 (id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,work_order_id INTEGER NOT NULL,mechanic_account_id INTEGER NOT NULL,mechanic_name TEXT NOT NULL,machine TEXT NOT NULL,fault_found TEXT,corrective_action TEXT,parts_used TEXT,hour_meter REAL,before_reading TEXT,after_reading TEXT,start_time TEXT,finish_time TEXT,checklist_confirmed INTEGER NOT NULL DEFAULT 0,before_photo_key TEXT,after_photo_key TEXT,status TEXT NOT NULL DEFAULT 'not_started',rejection_count INTEGER NOT NULL DEFAULT 0,discrepancy_count INTEGER NOT NULL DEFAULT 0,rework_count INTEGER NOT NULL DEFAULT 0,repeat_failure INTEGER NOT NULL DEFAULT 0,repeat_of_work_order_id INTEGER,submitted_at TEXT,verified_at TEXT,verifier_account_id INTEGER,verifier_name TEXT,verifier_role TEXT,verifier_notes TEXT,updated_at TEXT NOT NULL,UNIQUE(company_id,work_order_id))`
  ])await env.DB.prepare(q).run();
  const get=(key:string)=>sections.find(x=>x.key===key)?.rows||[],stmts:D1PreparedStatement[]=[];
  const sites=new Set<string>();for(const r of [...get("fleet"),...get("production")]){const n=normal(r),site=txt(n.site||n.sitearea,120);if(site)sites.add(site)}
  for(const site of sites)stmts.push(env.DB.prepare("INSERT INTO company_sites(company_id,name,code,active,created_at) SELECT ?,?,?,1,? WHERE NOT EXISTS(SELECT 1 FROM company_sites WHERE company_id=? AND lower(name)=lower(?))").bind(s.companyId,site,site.toUpperCase().replace(/[^A-Z0-9]+/g,"-").slice(0,20),now,s.companyId,site));
  stmts.push(env.DB.prepare("DELETE FROM daily_reports_v3 WHERE company_id=? AND source_file=?").bind(s.companyId,source));
  stmts.push(env.DB.prepare("DELETE FROM production_records WHERE company_id=? AND source_file=?").bind(s.companyId,source));
  for(const raw of get("production")){const n=normal(raw),x=parseProduction(raw,12);if(!x)continue;const basis=lower(n.capturebasis)==="time"?"time":"hour_meter",start=n.hourmeterstart===""?null:num(n.hourmeterstart),end=n.hourmeterend===""?null:num(n.hourmeterend);stmts.push(env.DB.prepare("INSERT INTO daily_reports_v3(company_id,report_date,site,fleet_number,activity,capture_basis,time_value,time_unit,hour_meter_start,hour_meter_end,duration_hours,tonnes,fault_reason,breakdown_start,breakdown_end,severity,source_kind,source_file,created_by,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,x.date,x.site,x.fleet,txt(n.activity||"operating"),basis,basis==="time"?x.operating:null,basis==="time"?"hours":null,start,end,x.operating,x.tonnes,x.fault||null,null,null,x.severity,"zip_import",source,s.accountId,txt(n.status||"saved"),now));stmts.push(env.DB.prepare("INSERT INTO production_records(company_id,report_date,fleet_number,shift_hours,planned_downtime,unplanned_downtime,operating_hours,productive_hours,tonnes,source_file,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,x.date,x.fleet,x.shift,x.planned,x.unplanned,x.operating,x.productive,x.tonnes,source,now))}
  stmts.push(env.DB.prepare("DELETE FROM events WHERE company_id=? AND action LIKE ?").bind(s.companyId,`${marker}%`));
  for(const raw of [...get("breakdowns"),...get("maintenance")]){const n=normal(raw),maintenance=!!n.maintenanceid,fleet=txt(n.fleetnumber,120);if(!fleet)continue;const description=txt(n.reason||n.workscope||"Maintenance service",500);stmts.push(env.DB.prepare("INSERT INTO events(company_id,fleet_number,event_type,severity,system_name,component,description,opened_at,closed_at,downtime_hours,status,action,spares_status,expected_return,oil_litres_lost,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,fleet,maintenance?"maintenance":"breakdown",lower(n.severity|| (lower(n.servicestatus)==="overdue"?"high":"medium")),txt(n.system||"Maintenance"),txt(n.component||"Service"),description,txt(n.openedat||n.planneddate||now),txt(n.closedat||n.completeddate)||null,num(n.downtimehours),lower(n.status||n.servicestatus||"open"),`${marker} ${txt(n.action||n.workscope||"Imported test record")}`,txt(n.sparesstatus)||null,txt(n.expectedreturn)||null,num(n.oillitreslost),now))}
  stmts.push(env.DB.prepare("DELETE FROM work_orders WHERE company_id=? AND title LIKE ?").bind(s.companyId,`${marker}%`));
  for(const raw of get("work_orders")){const n=normal(raw);stmts.push(env.DB.prepare("INSERT INTO work_orders(company_id,fleet_number,title,priority,assigned_to,due_at,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(s.companyId,txt(n.fleetnumber),`${marker} ${txt(n.title)}`,lower(n.priority||"medium"),txt(n.assignedto)||null,txt(n.dueat)||null,lower(n.status||"open"),txt(n.createdat||now)))}
  stmts.push(env.DB.prepare("DELETE FROM machine_telemetry_v1 WHERE company_id=? AND source=?").bind(s.companyId,source));
  for(const raw of get("telemetry")){const n=normal(raw);stmts.push(env.DB.prepare("INSERT INTO machine_telemetry_v1(company_id,machine_id,recorded_at,engine_hours,ignition_status,fuel_level,hydraulic_pressure,hydraulic_oil_level,engine_oil_pressure,coolant_temperature,rpm,engine_load,fault_code,source,raw_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,txt(n.fleetnumber),txt(n.recordedat||now),num(n.enginehours),txt(n.ignitionstatus),num(n.fuellevel),num(n.hydraulicpressure),num(n.hydraulicoillevel),num(n.engineoilpressure),num(n.coolanttemperature),num(n.rpm),num(n.engineload),txt(n.faultcode)||null,source,JSON.stringify(raw),now))}
  stmts.push(env.DB.prepare("DELETE FROM telemetry_alerts_v1 WHERE company_id=? AND details LIKE ?").bind(s.companyId,`${marker}%`));
  for(const raw of get("telemetry_alerts")){const n=normal(raw);stmts.push(env.DB.prepare("INSERT INTO telemetry_alerts_v1(company_id,machine_id,telemetry_id,alert_type,severity,title,details,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(s.companyId,txt(n.fleetnumber),0,txt(n.alerttype),lower(n.severity||"medium"),txt(n.title),`${marker} ${txt(n.details)}`,lower(n.status||"open"),txt(n.createdat||now)))}
  stmts.push(env.DB.prepare("DELETE FROM purchase_orders WHERE company_id=? AND notes LIKE ?").bind(s.companyId,`${marker}%`));
  for(const raw of get("purchase_orders")){const n=normal(raw);stmts.push(env.DB.prepare("INSERT INTO purchase_orders(company_id,order_number,document_type,supplier,store_contact,fleet_number,description,amount,order_date,expected_delivery,actual_delivery,payment_status,order_status,responsible_person,reminder_email,reminder_sms,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,txt(n.ordernumber),"purchase_order",txt(n.supplier),txt(n.storecontact)||null,txt(n.fleetnumber)||null,txt(n.description),num(n.amount),txt(n.orderdate),txt(n.expecteddelivery)||null,txt(n.actualdelivery)||null,lower(n.paymentstatus||"not_paid"),lower(n.orderstatus||"ordered"),txt(n.responsibleperson)||null,num(n.reminderemail,1),0,`${marker} ${txt(n.notes)}`,now,now))}
  stmts.push(env.DB.prepare("DELETE FROM approvals_v3 WHERE company_id=? AND title LIKE ?").bind(s.companyId,`${marker}%`));
  for(const raw of get("approvals")){const n=normal(raw);stmts.push(env.DB.prepare("INSERT INTO approvals_v3(company_id,approval_type,title,submitted_by,details,status,created_at,reviewed_at) VALUES(?,?,?,?,?,?,?,?)").bind(s.companyId,txt(n.approvaltype),`${marker} ${txt(n.title)}`,txt(n.submittedby),txt(n.details),lower(n.status||"pending"),txt(n.createdat||now),txt(n.reviewedat)||null))}
  await batchRun(env,stmts,75);
  const work=await all(env,"SELECT id,fleet_number fleet,title FROM work_orders WHERE company_id=? AND title LIKE ? ORDER BY id",[s.companyId,`${marker}%`]);
  const cards=get("job_cards"),cardStmts:D1PreparedStatement[]=[];for(let i=0;i<Math.min(cards.length,work.length);i++){const n=normal(cards[i]),w=work[i];cardStmts.push(env.DB.prepare("INSERT OR REPLACE INTO mechanic_job_evidence_v1(company_id,work_order_id,mechanic_account_id,mechanic_name,machine,fault_found,corrective_action,parts_used,hour_meter,start_time,finish_time,checklist_confirmed,status,submitted_at,verified_at,verifier_account_id,verifier_name,verifier_role,verifier_notes,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,num(w.id),s.accountId,txt(n.mechanicname),txt(n.fleetnumber),txt(n.faultfound),txt(n.correctiveaction),txt(n.partsused),num(n.hourmeter),txt(n.starttime)||null,txt(n.finishtime)||null,lower(n.status)==="completed"?1:0,lower(n.status||"not_started"),txt(n.finishtime)||null,txt(n.finishtime)||null,txt(n.finishtime)?s.accountId:null,txt(n.verifiername)||null,txt(n.verifiername)?"supervisor":null,txt(n.verifiernotes)||null,now))}if(cardStmts.length)await batchRun(env,cardStmts,75);
}

async function importZip(req:Request,env:Env,s:Session){
  if(!["company_admin","admin"].includes(s.role))return redirect("Company Administrator authority is required.","err");
  const form=await req.formData(),csrf=txt(form.get("csrf")),file=form.get("file");
  if(csrf!==await hash(s.token+"|trial-demo"))return redirect("Security check failed. Sign in again.","err");
  if(!(file instanceof File)||!/\.zip$/i.test(file.name)||file.size===0)return redirect("Choose a non-empty ZIP package.","err");
  if(file.size>20*1024*1024)return redirect("ZIP package is too large. Keep it below 20 MB.","err");
  await ensure(env);
  const rawBytes=new Uint8Array(await file.arrayBuffer()),entries=await unzip(rawBytes),structuredEntries=entries.filter(e=>/\.(csv|xlsx|xls)$/i.test(e.name)),documentEntries=entries.filter(e=>/\.(pdf|doc|docx)$/i.test(e.name));
  if(!structuredEntries.length)return redirect("No CSV or Excel files were found inside the ZIP package. Word and PDF files can be saved as supporting documents but cannot populate dashboard tables.","err");
  const sections=structuredEntries.flatMap(e=>e.name.toLowerCase().endsWith(".csv")?[{name:e.name,key:sectionKey(e.name),rows:parseCsv(e.bytes)}]:parseExcel(e.name,e.bytes)),fleet=sections.find(x=>x.key==="fleet"),production=sections.find(x=>x.key==="production");
  if(!production)return redirect("ZIP package must contain a Daily Production or Daily Report CSV/Excel file or worksheet.","err");
  let fleetMsg="";if(fleet){const r=await importFleet(env,s,fleet.rows);fleetMsg=` ${r.created} fleet unit(s) registered and ${r.updated} updated.`}
  let objectKey="";if(env.BUCKET){objectKey=`company/${s.companyId}/trial-demo/packages/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;await env.BUCKET.put(objectKey,rawBytes,{httpMetadata:{contentType:"application/zip"}})}
  const now=new Date().toISOString(),pkg=await env.DB.prepare("INSERT INTO demo_zip_packages_v1(company_id,package_name,object_key,imported_by,imported_at) VALUES(?,?,?,?,?)").bind(s.companyId,file.name,objectKey||null,s.accountId,now).run(),packageId=num(pkg.meta?.last_row_id);
  const secStmts=sections.map(sec=>env.DB.prepare("INSERT INTO demo_zip_sections_v1(package_id,company_id,section_key,file_name,row_count,data_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(packageId,s.companyId,sec.key,sec.name,sec.rows.length,JSON.stringify(sec.rows),now));
  if(secStmts.length)await batchRun(env,secStmts);
  if(env.BUCKET&&documentEntries.length){for(const doc of documentEntries){const safeName=doc.name.split("/").pop()?.replace(/[^a-zA-Z0-9._-]/g,"-")||"supporting-document";const key=`company/${s.companyId}/documents/zip-${packageId}-${crypto.randomUUID()}-${safeName}`,ext=safeName.toLowerCase().split(".").pop(),contentType=ext==="pdf"?"application/pdf":ext==="docx"?"application/vnd.openxmlformats-officedocument.wordprocessingml.document":"application/msword";await env.BUCKET.put(key,doc.bytes,{httpMetadata:{contentType}});await env.DB.prepare("INSERT INTO contractor_documents(company_id,uploaded_by,file_name,object_key,content_type,size_bytes,category,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(s.companyId,s.accountId,safeName,key,contentType,doc.bytes.byteLength,"ZIP supporting document",now).run()}}
  await importLiveSections(env,s,sections,file.name);

  const period=previousMonth(),settings=await first(env,"SELECT operating_hours hours FROM company_settings_v3 WHERE company_id=?",[s.companyId]).catch(()=>null),fleetRows=await all(env,"SELECT fleet_number fleet FROM machines WHERE company_id=?",[s.companyId]),fleets=new Map(fleetRows.map(x=>[lower(x.fleet),txt(x.fleet)]));
  if(!fleets.size)return redirect("Register or import the fleet before uploading historical reports.","err");
  const parsed:DemoRow[]=[],unmatched=new Set<string>();let outside=0;
  for(const r of production.rows){const x=parseProduction(r,num(settings?.hours,24));if(!x)continue;if(x.date<period.start||x.date>period.end){outside++;continue}const canonical=fleets.get(lower(x.fleet));if(!canonical){unmatched.add(x.fleet);continue}x.fleet=canonical;parsed.push(x)}
  if(!parsed.length)return redirect(`No matching ${period.label} rows were found. Check dates and fleet numbers.${unmatched.size?` Unmatched: ${[...unmatched].slice(0,5).join(", ")}.`:""}`,"err");
  const ins=await env.DB.prepare("INSERT INTO demo_import_batches_v1(company_id,source_file,object_key,period_start,period_end,total_rows,matched_rows,unmatched_rows,outside_rows,imported_by,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(s.companyId,file.name,objectKey||null,period.start,period.end,production.rows.length,parsed.length,unmatched.size,outside,s.accountId,now).run(),batch=num(ins.meta?.last_row_id);
  const recStmts=parsed.map(x=>env.DB.prepare("INSERT INTO demo_import_records_v1(batch_id,company_id,report_date,site,fleet_number,shift_hours,planned_downtime,unplanned_downtime,operating_hours,productive_hours,tonnes,fault_reason,severity,hour_meter,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(batch,s.companyId,x.date,x.site,x.fleet,x.shift,x.planned,x.unplanned,x.operating,x.productive,x.tonnes,x.fault||null,x.severity,x.hourMeter,now));
  await batchRun(env,recStmts,100);
  const hm=new Map<string,number>();for(const x of parsed)if(x.hourMeter!=null)hm.set(lower(x.fleet),Math.max(hm.get(lower(x.fleet))||0,x.hourMeter));const hmStmts=[...hm.entries()].map(([fleet,hours])=>env.DB.prepare("UPDATE machines SET operating_hours=CASE WHEN operating_hours<? THEN ? ELSE operating_hours END WHERE company_id=? AND lower(fleet_number)=?").bind(hours,hours,s.companyId,fleet));if(hmStmts.length)await batchRun(env,hmStmts);
  return redirect(`${parsed.length} ${period.label} production row(s) imported successfully.${fleetMsg} ${unmatched.size} unmatched fleet number(s); ${outside} row(s) outside the previous month. ZIP sections saved: ${sections.map(x=>`${x.key} (${x.rows.length})`).join(", ")}.${documentEntries.length?` ${documentEntries.length} Word/PDF supporting document(s) saved to Documents.`:""}`);
}

function table(rows:Row[],limit=80){if(!rows.length)return`<p class="zip-empty">No rows.</p>`;const keys=Object.keys(rows[0]).slice(0,10),shown=rows.slice(0,limit);return`<div class="zip-table-wrap"><table class="zip-table"><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join("")}</tr></thead><tbody>${shown.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>${rows.length>limit?`<p class="zip-note">Showing first ${limit} of ${rows.length} rows.</p>`:""}`}
const zipCss=`<style id="sas-zip-package-css">.zip-import{margin-bottom:12px;border:1px solid #cbd8d2;background:#fff;border-radius:12px;padding:16px}.zip-import h2{margin:0 0 6px;font-size:16px}.zip-import p{font-size:11px;color:#64736f}.zip-upload{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end}.zip-package{margin-top:12px}.zip-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:10px}.zip-card{border:1px solid #dce5e1;border-radius:9px;padding:10px;background:#f9fbfa}.zip-card small,.zip-card b{display:block}.zip-card small{font-size:9px;color:#6b7a75}.zip-card b{font-size:18px;margin-top:4px}.zip-section{margin:9px 0;border:1px solid #e1e8e4;border-radius:9px;background:#fff}.zip-section summary{cursor:pointer;padding:11px;font-weight:800;font-size:12px}.zip-table-wrap{overflow:auto;max-height:400px;border-top:1px solid #edf1ef}.zip-table{width:100%;border-collapse:collapse;font-size:9px}.zip-table th{position:sticky;top:0;background:#f3f6f5;text-align:left;padding:7px;white-space:nowrap}.zip-table td{padding:7px;border-top:1px solid #edf1ef;white-space:nowrap}.zip-note,.zip-empty{padding:0 10px 10px;color:#718079;font-size:10px}@media(max-width:900px){.zip-summary{grid-template-columns:1fr 1fr}.zip-upload{display:block}}</style>`;
async function injectZip(req:Request,env:Env,s:Session,response:Response){if(req.method!=="GET"||new URL(req.url).pathname!=="/trial-demo")return response;const type=response.headers.get("content-type")||"";if(!type.includes("text/html")||response.status>=400)return response;await ensure(env);const pkg=await first(env,"SELECT * FROM demo_zip_packages_v1 WHERE company_id=? ORDER BY id DESC LIMIT 1",[s.companyId]);let packageHtml="";if(pkg){const secs=await all(env,"SELECT * FROM demo_zip_sections_v1 WHERE company_id=? AND package_id=? ORDER BY id",[s.companyId,num(pkg.id)]),parsed=secs.map(x=>({...x,rows:(()=>{try{return JSON.parse(String(x.data_json||"[]")) as Row[]}catch{return[] as Row[]}})()})),get=(k:string)=>parsed.find(x=>x.section_key===k);packageHtml=`<section class="panel zip-package"><h2>Complete ZIP Package · ${esc(pkg.package_name)}</h2><div class="zip-summary"><div class="zip-card"><small>Fleet</small><b>${num(get("fleet")?.row_count)}</b></div><div class="zip-card"><small>Production rows</small><b>${num(get("production")?.row_count)}</b></div><div class="zip-card"><small>Breakdowns</small><b>${num(get("breakdowns")?.row_count)}</b></div><div class="zip-card"><small>Work orders</small><b>${num(get("work_orders")?.row_count)}</b></div><div class="zip-card"><small>Commercial records</small><b>${num(get("quotations")?.row_count)+num(get("purchase_orders")?.row_count)+num(get("payments")?.row_count)}</b></div></div>${parsed.map(sec=>`<details class="zip-section" ${sec.section_key==="summary"?"open":""}><summary>${esc(String(sec.section_key).replaceAll("_"," ").toUpperCase())} · ${num(sec.row_count)} row(s) · ${esc(sec.file_name)}</summary>${table(sec.rows)}</details>`).join("")}</section>`}const csrf=await hash(s.token+"|trial-demo"),admin=["company_admin","admin"].includes(s.role),upload=admin?`<section class="zip-import"><h2>Import Full-Dashboard ZIP Test Package</h2><p>CSV and Excel files populate matching dashboards. Word and PDF files are saved as supporting documents.</p><form class="zip-upload" method="post" action="/trial-demo/import-zip" enctype="multipart/form-data"><input type="hidden" name="csrf" value="${csrf}"><label class="field">Full-dashboard ZIP package<input type="file" name="file" accept=".zip,application/zip" required></label><button class="btn" type="submit">Import ZIP & Populate Dashboards</button></form></section>`:"";let body=await response.text();body=body.replace("</head>",`${zipCss}</head>`);const marker='<div class="safe">',idx=body.indexOf(marker);if(idx!==-1)body=body.slice(0,idx)+upload+body.slice(idx);else body=body.replace('<main class="wrap">',`<main class="wrap">${upload}`);body=body.replace("</main>",`${packageHtml}</main>`);const h=new Headers(response.headers);h.set("cache-control","private, no-store,max-age=0");h.delete("content-length");return new Response(body,{status:response.status,headers:h})}

export default {async fetch(req:Request,env:Env,ctx:ExecutionContext):Promise<Response>{const url=new URL(req.url);if(req.method==="POST"&&url.pathname==="/trial-demo/import-zip"){const s=await session(req,env);if(!s)return new Response(null,{status:302,headers:{location:"/contractor-login?next=/trial-demo"}});try{return await importZip(req,env,s)}catch(e){return redirect(`ZIP import failed: ${e instanceof Error?e.message:String(e)}`,"err")}}const response=await currentApp.fetch(req,env as never,ctx as never);if(req.method==="GET"&&url.pathname==="/trial-demo"){const s=await session(req,env);if(s)try{return await injectZip(req,env,s,response)}catch(e){console.error("TRIAL_ZIP_UI_ERROR",e)}}return response},async scheduled(controller:ScheduledController,env:Env,ctx:ExecutionContext){return currentApp.scheduled(controller as never,env as never,ctx as never)}};
