import currentApp from "./router-company-ui-master";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime:number; cron:string; noRetry():void; }
interface Env { DB:D1Database; [key:string]:unknown; }
type Row=Record<string,unknown>;
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const txt=(v:unknown)=>String(v??"").trim();
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}
async function all(env:Env,sql:string,b:unknown[]=[]){try{return (await env.DB.prepare(sql).bind(...b).all<Row>()).results||[]}catch{return []}}
function previousMonth(ms:number){const d=new Date(ms);const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1));x.setUTCMonth(x.getUTCMonth()-1);return x.toISOString().slice(0,7)}
function range(month:string){const [y,m]=month.split("-").map(Number);return {start:`${month}-01`,end:new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}}
async function ensure(env:Env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS month_end_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,month_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ready',prepared_at TEXT NOT NULL,prepared_by TEXT NOT NULL DEFAULT 'system',closed_at TEXT,closed_by INTEGER,summary_json TEXT,UNIQUE(company_id,month_key))`).run()}
async function archiveCompany(env:Env,cid:number,month:string){const {start,end}=range(month);const existing=await first(env,"SELECT id FROM demo_import_batches_v1 WHERE company_id=? AND substr(period_start,1,7)=? ORDER BY id DESC LIMIT 1",[cid,month]);let batchId=num(existing?.id);const prod=await all(env,`SELECT report_date date,fleet_number fleet,shift_hours shift,planned_downtime planned,unplanned_downtime unplanned,operating_hours operating,productive_hours productive,tonnes FROM production_records WHERE company_id=? AND report_date>=? AND report_date<=? ORDER BY report_date,fleet_number`,[cid,start,end]);if(!prod.length)return;
if(!batchId){const admin=await first(env,"SELECT id FROM contractor_accounts WHERE company_id=? AND status='active' ORDER BY CASE WHEN role IN ('company_admin','admin') THEN 0 ELSE 1 END,id LIMIT 1",[cid]);const ins=await env.DB.prepare(`INSERT INTO demo_import_batches_v1(company_id,source_file,object_key,period_start,period_end,status,total_rows,matched_rows,unmatched_rows,outside_rows,imported_by,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(cid,`AUTO-MONTH-END:${month}`,null,start,end,"closed",prod.length,prod.length,0,0,num(admin?.id)||0,new Date().toISOString()).run();batchId=num(ins.meta?.last_row_id);for(const r of prod){const ev=await first(env,`SELECT description,severity FROM events WHERE company_id=? AND lower(fleet_number)=lower(?) AND date(opened_at)=date(?) ORDER BY id DESC LIMIT 1`,[cid,txt(r.fleet),txt(r.date)]);await env.DB.prepare(`INSERT INTO demo_import_records_v1(batch_id,company_id,report_date,site,fleet_number,shift_hours,planned_downtime,unplanned_downtime,operating_hours,productive_hours,tonnes,fault_reason,severity,hour_meter,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(batchId,cid,txt(r.date),"Historical",txt(r.fleet),num(r.shift),num(r.planned),num(r.unplanned),num(r.operating),num(r.productive),num(r.tonnes),txt(ev?.description)||null,txt(ev?.severity)||"medium",null,new Date().toISOString()).run()}}
const shift=prod.reduce((a,r)=>a+num(r.shift),0),planned=prod.reduce((a,r)=>a+num(r.planned),0),unplanned=prod.reduce((a,r)=>a+num(r.unplanned),0),operating=prod.reduce((a,r)=>a+num(r.operating),0),productive=prod.reduce((a,r)=>a+num(r.productive),0),tonnes=prod.reduce((a,r)=>a+num(r.tonnes),0),available=Math.max(0,shift-planned-unplanned);const ev=await first(env,`SELECT COUNT(*) events,SUM(downtime_hours) eventDowntime FROM events WHERE company_id=? AND date(opened_at)>=date(?) AND date(opened_at)<=date(?)`,[cid,start,end]);const summary={month,rows:prod.length,machines:new Set(prod.map(r=>txt(r.fleet))).size,tonnes,planned,unplanned,operating,productive,availability:shift?available/shift*100:0,utilisation:available?operating/available*100:0,events:num(ev?.events),eventDowntime:num(ev?.eventDowntime)};await env.DB.prepare(`INSERT INTO month_end_v1(company_id,month_key,status,prepared_at,prepared_by,closed_at,closed_by,summary_json) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(company_id,month_key) DO UPDATE SET status='closed',closed_at=COALESCE(month_end_v1.closed_at,excluded.closed_at),summary_json=excluded.summary_json`).bind(cid,month,"closed",new Date().toISOString(),"automatic-month-end",new Date().toISOString(),null,JSON.stringify(summary)).run()}
async function runArchive(env:Env,ms:number){await ensure(env);const month=previousMonth(ms);const companies=await all(env,"SELECT id FROM companies WHERE lower(licence_status) IN ('active','trial')");for(const c of companies){try{await archiveCompany(env,num(c.id),month)}catch(e){console.error("AUTO_MONTH_ARCHIVE_ERROR",c.id,month,e)}}}
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){return currentApp.fetch(req,env as never,ctx as never)},async scheduled(c:ScheduledController,env:Env,ctx:ExecutionContext){await runArchive(env,c.scheduledTime);const app=currentApp as unknown as {scheduled?:(c:ScheduledController,e:Env,x:ExecutionContext)=>Promise<void>|void};if(app.scheduled)return app.scheduled(c,env,ctx)}};
