import currentApp from "./router-accountability";
import { sindaneLogoDataUri } from "./sindane-logo-data";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface Env { [key:string]: unknown; }

const THEME="#061827";
const GREEN="#11975c";

function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));}
function html(body:string,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-frame-options":"DENY","referrer-policy":"same-origin","content-security-policy":"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; manifest-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"}});}
function redirect(path:string){return new Response(null,{status:302,headers:{location:path,"cache-control":"no-store"}});}

function contractorIconSvg(){const logo=sindaneLogoDataUri();return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="92" fill="#061827"/><rect x="26" y="26" width="460" height="460" rx="74" fill="#0a1c29" stroke="#11975c" stroke-width="8"/><image href="${logo}" x="62" y="80" width="388" height="300" preserveAspectRatio="xMidYMid meet"/><text x="256" y="423" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="29" font-weight="800" fill="#ffffff">TMM ASSET HEALTH</text><text x="256" y="458" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="15" font-weight="700" letter-spacing="4" fill="#e3a500">TRACK. PREVENT. PERFORM.</text></svg>`;}
function ownerIconSvg(){const logo=sindaneLogoDataUri();return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="92" fill="#061827"/><rect x="26" y="26" width="460" height="460" rx="74" fill="#10283a" stroke="#e3a500" stroke-width="8"/><image href="${logo}" x="68" y="65" width="376" height="285" preserveAspectRatio="xMidYMid meet"/><text x="256" y="396" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="27" font-weight="800" fill="#ffffff">PLATFORM OWNER</text><text x="256" y="437" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="18" font-weight="800" fill="#11975c">SINDANE ASSET SOLUTIONS</text><text x="256" y="467" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="13" font-weight="700" letter-spacing="3" fill="#e3a500">TRACK. PREVENT. PERFORM.</text></svg>`;}

function contractorManifest(){return JSON.stringify({id:"/tmm-contractor-app",name:"TMM Asset Health",short_name:"TMM Asset Health",description:"TMM fleet, maintenance, breakdown, production, reporting and accountability software for licensed contractors.",start_url:"/contractor-login",scope:"/",display:"standalone",orientation:"any",background_color:"#f5f7f9",theme_color:THEME,categories:["business","productivity"],icons:[{src:"/app-icon.svg",sizes:"any",type:"image/svg+xml",purpose:"any maskable"}]},null,2);}
function ownerManifest(){return JSON.stringify({id:"/sindane-platform-owner-app",name:"Sindane Platform Owner",short_name:"Sindane Owner",description:"Private Sindane Asset Solutions Platform Owner application for TMM Asset Health administration, licences, contractors, payments and commercial control.",start_url:"/owner-login",scope:"/",display:"standalone",orientation:"any",background_color:"#f5f7f9",theme_color:THEME,categories:["business","productivity"],icons:[{src:"/owner-app-icon.svg",sizes:"any",type:"image/svg+xml",purpose:"any maskable"}]},null,2);}

const registerJs=`(()=>{if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{}));}})();`;
const swJs=`self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;e.respondWith(fetch(e.request).catch(()=>new Response('TMM Asset Health requires an internet connection.',{status:503,headers:{'content-type':'text/plain; charset=utf-8'}})));});`;

function installScript(appLabel:string){return `<script>let deferredInstall=null;const btn=document.getElementById('installBtn');const note=document.getElementById('installNote');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;btn.disabled=false;btn.textContent='Install ${appLabel}';note.textContent='Ready to install on this computer.';});btn.addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;return;}note.innerHTML='If the install window does not open, use the browser menu and choose <b>Install ${appLabel}</b> or <b>Apps → Install this site as an app</b>.';});window.addEventListener('appinstalled',()=>{note.textContent='${appLabel} is installed. Open it from your Desktop or Start menu.';btn.disabled=true;btn.textContent='Installed';});</script>`;}

function page(title:string,content:string,manifestHref:string,iconHref:string,appLabel:string,withInstall=false){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="${THEME}"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="application-name" content="${esc(appLabel)}"><link rel="manifest" href="${manifestHref}"><link rel="icon" href="${iconHref}" type="image/svg+xml"><link rel="apple-touch-icon" href="${iconHref}"><title>${esc(title)}</title><style>*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:linear-gradient(145deg,#061827,#0a2132);font-family:Inter,Arial,Helvetica,sans-serif;color:#102035}.wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(650px,100%);background:#fff;border-radius:22px;overflow:hidden;box-shadow:0 22px 70px rgba(0,0,0,.28)}.brand{background:#071a29;padding:28px;text-align:center;border-bottom:5px solid ${GREEN}}.brand img{width:230px;height:145px;object-fit:contain}.brand h1{margin:8px 0 2px;color:#fff;font-size:30px}.brand p{margin:0;color:#e6a600;font-size:12px;font-weight:900;letter-spacing:4px}.body{padding:30px}.body h2{margin:0 0 8px;font-size:25px}.muted{font-size:13px;color:#657386;line-height:1.55}.btn{display:block;width:100%;text-align:center;text-decoration:none;border:0;border-radius:10px;padding:14px 16px;font-weight:900;font-size:14px;cursor:pointer;background:${GREEN};color:#fff}.btn.dark{background:#10283a}.btn.gray{background:#edf2f5;color:#213648}.btn:disabled{opacity:.65;cursor:not-allowed}.foot{padding:15px 30px;background:#f4f7f8;font-size:10px;color:#667583;text-align:center}@media(max-width:620px){.body{padding:22px}.brand img{width:190px;height:120px}.brand h1{font-size:24px}}</style><script src="/pwa-register.js" defer></script></head><body><main class="wrap"><section class="card"><header class="brand"><img src="${sindaneLogoDataUri()}" alt="Sindane Asset Solutions"><h1>${esc(appLabel)}</h1><p>TRACK. PREVENT. PERFORM.</p></header><div class="body">${content}</div><footer class="foot">Sindane Asset Solutions · Secure cloud-connected software</footer></section></main>${withInstall?installScript(appLabel):''}</body></html>`;}

function contractorInstallPage(){return page("Install TMM Asset Health",`<h2>Install Contractor / Staff App</h2><p class="muted">For Company Admins, Mine Managers, Engineers, Supervisors and Mechanics. After installation the app opens directly to the contractor login.</p><button class="btn" id="installBtn">Install TMM Asset Health</button><p id="installNote" class="muted" style="margin-top:12px">Click Install. If the browser needs a moment, the install option will become available automatically.</p><div style="margin-top:16px"><a class="btn gray" href="/contractor-login">Back to Contractor Login</a></div>`,`/app.webmanifest`,`/app-icon.svg`,`TMM Asset Health`,true);}
function ownerInstallPage(){return page("Install Sindane Platform Owner",`<h2>Install Your Owner App</h2><p class="muted">This private app is for the Sindane Asset Solutions software owner. After installation it opens directly to the Platform Owner login, not the contractor login.</p><button class="btn dark" id="installBtn">Install Sindane Platform Owner</button><p id="installNote" class="muted" style="margin-top:12px">Click Install. This owner app is separate from the contractor/staff app.</p><div style="margin-top:16px"><a class="btn gray" href="/owner-login">Back to Owner Login</a></div>`,`/owner-app.webmanifest`,`/owner-app-icon.svg`,`Sindane Platform Owner`,true);}

async function injectPwa(res:Response,path:string){const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let out=await res.text();const owner=path.startsWith("/owner");const manifestHref=owner?"/owner-app.webmanifest":"/app.webmanifest";const iconHref=owner?"/owner-app-icon.svg":"/app-icon.svg";const appName=owner?"Sindane Platform Owner":"TMM Asset Health";const head=`<meta name="theme-color" content="${THEME}"><meta name="application-name" content="${appName}"><link rel="manifest" href="${manifestHref}"><link rel="icon" href="${iconHref}" type="image/svg+xml"><script src="/pwa-register.js" defer></script>`;if(out.includes("</head>"))out=out.replace("</head>",head+"</head>");const h=new Headers(res.headers);h.set("cache-control","private, no-store");return new Response(out,{status:res.status,statusText:res.statusText,headers:h});}

export default{async fetch(req:Request,env:Env,ctx:ExecutionContext):Promise<Response>{const url=new URL(req.url),p=url.pathname;if(p==="/app.webmanifest")return new Response(contractorManifest(),{headers:{"content-type":"application/manifest+json; charset=utf-8","cache-control":"no-cache"}});if(p==="/owner-app.webmanifest")return new Response(ownerManifest(),{headers:{"content-type":"application/manifest+json; charset=utf-8","cache-control":"no-cache"}});if(p==="/app-icon.svg")return new Response(contractorIconSvg(),{headers:{"content-type":"image/svg+xml; charset=utf-8","cache-control":"public, max-age=86400"}});if(p==="/owner-app-icon.svg")return new Response(ownerIconSvg(),{headers:{"content-type":"image/svg+xml; charset=utf-8","cache-control":"public, max-age=86400"}});if(p==="/pwa-register.js")return new Response(registerJs,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"public, max-age=3600"}});if(p==="/sw.js")return new Response(swJs,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-cache","service-worker-allowed":"/"}});if(p==="/app-start")return redirect("/contractor-login");if(p==="/install-app")return html(contractorInstallPage());if(p==="/install-owner-app")return html(ownerInstallPage());const res=await currentApp.fetch(req,env as never,ctx);return injectPwa(res,p);}};
