import currentApp from "./router-history-library";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime:number; cron:string; noRetry():void; }
interface Env { DB:D1Database; [key:string]:unknown; }
type Row=Record<string,unknown>;
type Session={companyId:number;accountId:number;role:string;fullName:string;companyName:string;token:string};
const COOKIE="sas_contractor_v2",enc=new TextEncoder();
const txt=(v:unknown,n=300)=>String(v??"").trim().slice(0,n);
const low=(v:unknown)=>txt(v).toLowerCase();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
function cookie(req:Request){for(const p of (req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===COOKIE)return p.slice(i+1).trim()}return ""}
async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))),b=>b.toString(16).padStart(2,"0")).join("")}
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}
async function all(env:Env,sql:string,b:unknown[]=[]){try{return (await env.DB.prepare(sql).bind(...b).all<Row>()).results||[]}catch{return []}}
async function session(req:Request,env:Env):Promise<Session|null>{const token=cookie(req);if(!token)return null;const r=await first(env,`SELECT s.company_id companyId,s.account_id accountId,a.full_name fullName,COALESCE(NULLIF(s.active_role,''),a.role) role,c.name companyName FROM contractor_sessions s JOIN contractor_accounts a ON a.id=s.account_id JOIN companies c ON c.id=s.company_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND a.status='active' LIMIT 1`,[await hash(token)]);return r?{companyId:num(r.companyId),accountId:num(r.accountId),role:low(r.role),fullName:txt(r.fullName),companyName:txt(r.companyName),token}:null}
function monthRange(month:string){const [y,m]=month.split("-").map(Number),start=`${month}-01`,end=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);return{start,end}}
function prevMonth(base=new Date()){const d=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth(),1));d.setUTCMonth(d.getUTCMonth()-1);return d.toISOString().slice(0,7)}
function currentMonth(base=new Date()){return base.toISOString().slice(0,7)}
function label(month:string){const [y,m]=month.split("-").map(Number);return new Date(Date.UTC(y,m-1,1)).toLocaleString("en-ZA",{month:"long",year:"numeric",timeZone:"UTC"})}
async function ensure(env:Env){for(const q of [
`CREATE TABLE IF NOT EXISTS month_end_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,month_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ready',prepared_at TEXT NOT NULL,prepared_by TEXT NOT NULL DEFAULT 'system',closed_at TEXT,closed_by INTEGER,summary_json TEXT,UNIQUE(company_id,month_key))`,
`CREATE INDEX IF NOT EXISTS idx_month_end_company ON month_end_v1(company_id,month_key,status)`])await env.DB.prepare(q).run()}
async function summary(env:Env,cid:number,month:string){const {start,end}=monthRange(month);const p=await first(env,`SELECT COUNT(*) rows,COUNT(DISTINCT fleet_number) machines,SUM(shift_hours) shift,SUM(planned_downtime) planned,SUM(unplanned_downtime) unplanned,SUM(operating_hours) operating,SUM(productive_hours) productive,SUM(tonnes) tonnes FROM production_records WHERE company_id=? AND report_date>=? AND report_date<=?`,[cid,start,end]);const events=await first(env,`SELECT COUNT(*) events,SUM(downtime_hours) eventDowntime FROM events WHERE company_id=? AND date(opened_at)>=date(?) AND date(opened_at)<=date(?)`,[cid,start,end]);const shift=num(p?.shift),planned=num(p?.planned),unplanned=num(p?.unplanned),available=Math.max(0,shift-planned-unplanned),operating=num(p?.operating),productive=num(p?.productive);return {month,rows:num(p?.rows),machines:num(p?.machines),tonnes:num(p?.tonnes),planned,unplanned,operating,productive,availability:shift?available/shift*100:0,utilisation:available?operating/available*100:0,events:num(events?.events),eventDowntime:num(events?.eventDowntime)}}
async function prepare(env:Env,cid:number,month:string,by="system"){await ensure(env);const s=await summary(env,cid,month);if(!s.rows)return null;await env.DB.prepare(`INSERT INTO month_end_v1(company_id,month_key,status,prepared_at,prepared_by,summary_json) VALUES(?,?,?,?,?,?) ON CONFLICT(company_id,month_key) DO UPDATE SET summary_json=excluded.summary_json,prepared_at=CASE WHEN month_end_v1.status='closed' THEN month_end_v1.prepared_at ELSE excluded.prepared_at END,prepared_by=CASE WHEN month_end_v1.status='closed' THEN month_end_v1.prepared_by ELSE excluded.prepared_by END`).bind(cid,month,"ready",new Date().toISOString(),by,JSON.stringify(s)).run();return s}
async function snapshotHistory(env:Env,s:Session,month:string){const {start,end}=monthRange(month);const existing=await first(env,"SELECT id FROM demo_import_batches_v1 WHERE company_id=? AND substr(period_start,1,7)=? ORDER BY id DESC LIMIT 1",[s.companyId,month]);let batchId=num(existing?.id);if(!batchId){const prod=await all(env,`SELECT report_date date,fleet_number fleet,shift_hours shift,planned_downtime planned,unplanned_downtime unplanned,operating_hours operating,productive_hours productive,tonnes FROM production_records WHERE company_id=? AND report_date>=? AND report_date<=? ORDER BY report_date,fleet_number`,[s.companyId,start,end]);if(!prod.length)throw new Error(`No ${label(month)} production records were found.`);const ins=await env.DB.prepare(`INSERT INTO demo_import_batches_v1(company_id,source_file,object_key,period_start,period_end,status,total_rows,matched_rows,unmatched_rows,outside_rows,imported_by,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(s.companyId,`MONTH-END:${month}`,null,start,end,"closed",prod.length,prod.length,0,0,s.accountId,new Date().toISOString()).run();batchId=num(ins.meta?.last_row_id);for(const r of prod){const ev=await first(env,`SELECT description,severity FROM events WHERE company_id=? AND lower(fleet_number)=lower(?) AND date(opened_at)=date(?) ORDER BY id DESC LIMIT 1`,[s.companyId,txt(r.fleet),txt(r.date)]);await env.DB.prepare(`INSERT INTO demo_import_records_v1(batch_id,company_id,report_date,site,fleet_number,shift_hours,planned_downtime,unplanned_downtime,operating_hours,productive_hours,tonnes,fault_reason,severity,hour_meter,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(batchId,s.companyId,txt(r.date),"Historical",txt(r.fleet),num(r.shift),num(r.planned),num(r.unplanned),num(r.operating),num(r.productive),num(r.tonnes),txt(ev?.description)||null,low(ev?.severity)||"medium",null,new Date().toISOString()).run()}}
return batchId}
function html(body:string,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
function redirect(url:string){return new Response(null,{status:303,headers:{location:url,"cache-control":"no-store"}})}
function css(){return `<style>*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#10223b;font-family:Arial,sans-serif}.bar{background:#0d1b31;color:#fff;padding:14px 20px}.bar a{color:#fff;text-decoration:none;font-weight:800}.wrap{max-width:1200px;margin:auto;padding:24px}.hero,.panel,.kpi{background:#fff;border:1px solid #dfe6ef;border-radius:13px}.hero,.panel{padding:18px}.hero{display:flex;justify-content:space-between;gap:18px;align-items:center}.hero h1{margin:4px 0}.hero small{font-weight:900;color:#72809a}.badge{background:#fff3cc;border:1px solid #d8b23c;border-radius:99px;padding:6px 10px;font-size:10px;font-weight:900}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:14px 0}.kpi{padding:15px}.kpi small,.kpi b{display:block}.kpi small{font-size:9px;color:#718099;font-weight:900}.kpi b{font-size:24px;margin-top:7px}.btn{border:0;border-radius:8px;padding:11px 14px;background:#14223a;color:#fff;font-weight:900;cursor:pointer}.btn.green{background:#10975b}.note{font-size:11px;color:#66768d;line-height:1.5}.ok{background:#e8f7ef;color:#14693f;padding:10px;border-radius:8px;margin-bottom:12px}.warn{background:#fff7dc;color:#795b00;padding:10px;border-radius:8px;margin-bottom:12px}.table{width:100%;border-collapse:collapse;font-size:11px}.table th{text-align:left;background:#f5f7fa;padding:9px}.table td{padding:9px;border-bottom:1px solid #e8edf3}@media(max-width:800px){.kpis{grid-template-columns:1fr 1fr}.hero{display:block}}@media(max-width:500px){.kpis{grid-template-columns:1fr}}</style>`}
async function page(req:Request,env:Env,s:Session){await ensure(env);const month=prevMonth();await prepare(env,s.companyId,month,"system");const row=await first(env,"SELECT * FROM month_end_v1 WHERE company_id=? AND month_key=?",[s.companyId,month]);const sum=row?.summary_json?JSON.parse(String(row.summary_json)):await summary(env,s.companyId,month);const url=new URL(req.url),msg=txt(url.searchParams.get("msg"),500),closed=low(row?.status)==="closed";return html(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Month End · TMM Asset Health</title>${css()}</head><body><div class="bar"><a href="/contractor">← Dashboard</a></div><main class="wrap">${msg?`<div class="ok">${esc(msg)}</div>`:""}<section class="hero"><div><small>MONTH-END CONTROL · COMPANY ADMIN</small><h1>${esc(label(month))} Monthly Summary ${closed?"Closed":"Ready"}</h1><p class="note">The system prepares this automatically after month-end. Review it before publishing to Previous Months.</p></div><span class="badge">${closed?"CLOSED":"READY FOR REVIEW"}</span></section><div class="kpis"><div class="kpi"><small>Availability</small><b>${num(sum.availability).toFixed(1)}%</b></div><div class="kpi"><small>Utilisation</small><b>${num(sum.utilisation).toFixed(1)}%</b></div><div class="kpi"><small>Production</small><b>${num(sum.tonnes).toLocaleString("en-ZA",{maximumFractionDigits:0})} t</b></div><div class="kpi"><small>Breakdown events</small><b>${num(sum.events)}</b></div></div><section class="panel"><h2>Month close workflow</h2><p class="note">Current reporting month: <b>${esc(label(currentMonth()))}</b>. New daily reports belong to the new month automatically. Closing ${esc(label(month))} does not delete its information; it publishes a historical snapshot for every role under Previous Months.</p>${closed?`<p><b>${esc(label(month))} is closed.</b> Everyone can open it from Previous Months according to their role.</p><p><a class="btn green" href="/history?month=${esc(month)}">Open published month</a></p>`:`<form method="post" action="/month-end/close"><input type="hidden" name="month" value="${esc(month)}"><input type="hidden" name="csrf" value="${await hash(s.token+"|month-end")}"><button class="btn green" type="submit">Publish / Close ${esc(label(month))}</button></form><p class="note">Only the Company Admin can close a month. Email recipients are still selected separately from that month inside Previous Months.</p>`}</section></main></body></html>`)}
async function closeMonth(req:Request,env:Env,s:Session){if(!["company_admin","admin"].includes(s.role))return html("Company Administrator authority is required.",403);const f=await req.formData();if(txt(f.get("csrf"))!==await hash(s.token+"|month-end"))return html("Security check failed.",403);const month=txt(f.get("month"),7);if(month!==prevMonth())return html("Only the completed previous calendar month can be closed from this control.",400);await ensure(env);const sm=await prepare(env,s.companyId,month,"admin-review");if(!sm)return redirect(`/month-end?msg=${encodeURIComponent(`No ${label(month)} production data is available to close.`)}`);await snapshotHistory(env,s,month);await env.DB.prepare("UPDATE month_end_v1 SET status='closed',closed_at=?,closed_by=?,summary_json=? WHERE company_id=? AND month_key=?").bind(new Date().toISOString(),s.accountId,JSON.stringify(sm),s.companyId,month).run();return redirect(`/month-end?msg=${encodeURIComponent(`${label(month)} published successfully. ${label(currentMonth())} is the active reporting month.`)}`)}
function inject(body:string,s:Session){if(!["company_admin","admin"].includes(s.role))return body;const link=`<a href="/month-end" style="display:block;margin:8px 12px;padding:10px 12px;border-radius:8px;background:#0f9d63;color:#fff;text-decoration:none;font:800 12px Arial">▣ Month-End Review</a>`;if(body.includes("</nav>"))return body.replace("</nav>",`${link}</nav>`);return body}
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url),s=await session(req,env);if(s&&url.pathname==="/month-end"&&req.method==="GET"){if(!["company_admin","admin"].includes(s.role))return redirect("/contractor");return page(req,env,s)}if(s&&url.pathname==="/month-end/close"&&req.method==="POST")return closeMonth(req,env,s);const res=await currentApp.fetch(req,env as never,ctx as never);if(!s||req.method!=="GET")return res;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let body=await res.text();body=inject(body,s);const h=new Headers(res.headers);h.set("cache-control","private, no-store");h.delete("content-length");return new Response(body,{status:res.status,headers:h})},async scheduled(controller:ScheduledController,env:Env,ctx:ExecutionContext){await ensure(env);const m=prevMonth(new Date(controller.scheduledTime));const companies=await all(env,"SELECT id FROM companies WHERE lower(licence_status) IN ('active','trial')");for(const c of companies)await prepare(env,num(c.id),m,"system");const app=currentApp as unknown as {scheduled?:(c:ScheduledController,e:Env,x:ExecutionContext)=>Promise<void>|void};if(app.scheduled)return app.scheduled(controller,env,ctx)}};