import currentApp from "./router-accountability";
import { sindaneLogoDataUri } from "./sindane-logo-data";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface Env { [key:string]: unknown; }

const THEME="#061827";
const GREEN="#11975c";

function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));}
function html(body:string,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-frame-options":"DENY","referrer-policy":"same-origin","content-security-policy":"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; manifest-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"}});}

function appIconSvg(){const logo=sindaneLogoDataUri();return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="92" fill="#061827"/><rect x="26" y="26" width="460" height="460" rx="74" fill="#0a1c29" stroke="#11975c" stroke-width="8"/><image href="${logo}" x="62" y="92" width="388" height="300" preserveAspectRatio="xMidYMid meet"/><text x="256" y="431" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="30" font-weight="800" fill="#ffffff">TMM ASSET HEALTH</text><text x="256" y="461" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="16" font-weight="700" letter-spacing="4" fill="#e3a500">TRACK. PREVENT. PERFORM.</text></svg>`;}

function manifest(){return JSON.stringify({id:"/",name:"TMM Asset Health · Sindane Asset Solutions",short_name:"TMM Asset Health",description:"Secure TMM fleet, maintenance, breakdown, production, reporting and accountability software by Sindane Asset Solutions.",start_url:"/app-start",scope:"/",display:"standalone",orientation:"any",background_color:"#f5f7f9",theme_color:THEME,categories:["business","productivity"],icons:[{src:"/app-icon.svg",sizes:"any",type:"image/svg+xml",purpose:"any maskable"}],shortcuts:[{name:"Contractor Login",short_name:"Contractor",url:"/contractor-login",icons:[{src:"/app-icon.svg",sizes:"any",type:"image/svg+xml"}]},{name:"Platform Owner",short_name:"Owner",url:"/owner-login",icons:[{src:"/app-icon.svg",sizes:"any",type:"image/svg+xml"}]}]},null,2);}

const registerJs=`(()=>{if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{}));}})();`;
const swJs=`self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;e.respondWith(fetch(e.request).catch(()=>new Response('TMM Asset Health requires an internet connection.',{status:503,headers:{'content-type':'text/plain; charset=utf-8'}})));});`;

function installScript(){return `<script>let deferredInstall=null;const btn=document.getElementById('installBtn');const note=document.getElementById('installNote');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;btn.disabled=false;btn.textContent='Install TMM Asset Health';note.textContent='Ready to install on this device.';});btn.addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;btn.disabled=true;btn.textContent='Install requested';return;}note.innerHTML='If the install window does not open, use your browser menu and choose <b>Install TMM Asset Health</b> or <b>Apps → Install this site as an app</b>.';});window.addEventListener('appinstalled',()=>{note.textContent='TMM Asset Health is installed. You can open it from your Desktop or Start menu.';btn.disabled=true;btn.textContent='Installed';});</script>`;}

function page(title:string,content:string,withInstall=false){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="${THEME}"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="application-name" content="TMM Asset Health"><link rel="manifest" href="/app.webmanifest"><link rel="icon" href="/app-icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/app-icon.svg"><title>${esc(title)}</title><style>*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:linear-gradient(145deg,#061827,#0a2132);font-family:Inter,Arial,Helvetica,sans-serif;color:#102035}.wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(760px,100%);background:#fff;border-radius:22px;overflow:hidden;box-shadow:0 22px 70px rgba(0,0,0,.28)}.brand{background:#071a29;padding:28px;text-align:center;border-bottom:5px solid #11975c}.brand img{width:230px;height:145px;object-fit:contain}.brand h1{margin:8px 0 2px;color:#fff;font-size:30px}.brand p{margin:0;color:#e6a600;font-size:12px;font-weight:900;letter-spacing:4px}.body{padding:30px}.body h2{margin:0 0 8px;font-size:25px}.muted{font-size:13px;color:#657386;line-height:1.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px}.btn{display:block;text-align:center;text-decoration:none;border:0;border-radius:10px;padding:14px 16px;font-weight:900;font-size:14px;cursor:pointer;background:${GREEN};color:#fff}.btn.dark{background:#10283a}.btn.gray{background:#edf2f5;color:#213648}.btn:disabled{opacity:.65;cursor:not-allowed}.info{margin-top:18px;padding:14px;border:1px solid #dce5e9;border-radius:10px;background:#f7faf9;font-size:12px;line-height:1.55}.roles{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.role{padding:5px 8px;border-radius:999px;background:#e8f6ee;color:#087047;font-size:10px;font-weight:800}.foot{padding:15px 30px;background:#f4f7f8;font-size:10px;color:#667583;text-align:center}@media(max-width:620px){.grid{grid-template-columns:1fr}.body{padding:22px}.brand img{width:190px;height:120px}.brand h1{font-size:24px}}</style><script src="/pwa-register.js" defer></script></head><body><main class="wrap"><section class="card"><header class="brand"><img src="${sindaneLogoDataUri()}" alt="Sindane Asset Solutions"><h1>TMM Asset Health</h1><p>TRACK. PREVENT. PERFORM.</p></header><div class="body">${content}</div><footer class="foot">Sindane Asset Solutions · Secure cloud-connected TMM software</footer></section></main>${withInstall?installScript():''}</body></html>`;}

function startPage(){return page("TMM Asset Health",`<h2>Open TMM Asset Health</h2><p class="muted">One secure application for Sindane Asset Solutions and every licensed contractor. Your dashboard is selected automatically after you sign in.</p><div class="grid"><a class="btn" href="/contractor-login">Contractor / Staff Sign In</a><a class="btn dark" href="/owner-login">Sindane Platform Owner</a></div><div class="roles"><span class="role">Company Admin</span><span class="role">Mine Manager</span><span class="role">Engineer</span><span class="role">Supervisor</span><span class="role">Mechanic</span></div><div class="info"><b>Install on this computer:</b> use the Install App page below. Once installed, TMM Asset Health opens in its own desktop window and stays connected to the same live Cloudflare system.</div><div style="margin-top:12px"><a class="btn gray" href="/install-app">Install TMM Asset Health</a></div>`);}
function installPage(){return page("Install TMM Asset Health",`<h2>Install TMM Asset Health</h2><p class="muted">Install the software on this Windows PC without copying contractor data to the computer. The app stays connected to the secure Cloudflare system, so updates are automatic.</p><button class="btn" id="installBtn">Install TMM Asset Health</button><p id="installNote" class="muted" style="margin-top:12px">Click Install. If your browser needs a moment, the install option will become available automatically.</p><div class="info"><b>For contractors and employees:</b> send them this Install App link. They install the same app and sign in with the invitation/account you created. Engineer, Supervisor, Mechanic, Manager and Company Admin automatically open their own role dashboard — no separate installer is required.</div><div class="grid"><a class="btn gray" href="/app-start">Back to App Start</a><a class="btn dark" href="/contractor-login">Sign In Without Installing</a></div>`,true);}

async function injectPwa(res:Response){const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let out=await res.text();const head=`<meta name="theme-color" content="${THEME}"><meta name="application-name" content="TMM Asset Health"><link rel="manifest" href="/app.webmanifest"><link rel="icon" href="/app-icon.svg" type="image/svg+xml"><script src="/pwa-register.js" defer></script>`;if(out.includes("</head>"))out=out.replace("</head>",head+"</head>");const h=new Headers(res.headers);h.set("cache-control","private, no-store");return new Response(out,{status:res.status,statusText:res.statusText,headers:h});}

export default{async fetch(req:Request,env:Env,ctx:ExecutionContext):Promise<Response>{const url=new URL(req.url),p=url.pathname;if(p==="/app.webmanifest")return new Response(manifest(),{headers:{"content-type":"application/manifest+json; charset=utf-8","cache-control":"public, max-age=3600"}});if(p==="/app-icon.svg")return new Response(appIconSvg(),{headers:{"content-type":"image/svg+xml; charset=utf-8","cache-control":"public, max-age=86400"}});if(p==="/pwa-register.js")return new Response(registerJs,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"public, max-age=3600"}});if(p==="/sw.js")return new Response(swJs,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-cache","service-worker-allowed":"/"}});if(p==="/app-start")return html(startPage());if(p==="/install-app")return html(installPage());const res=await currentApp.fetch(req,env as never,ctx);return injectPwa(res);}};
