import currentApp from "./router-utilisation-target";

interface ExecutionContext { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void; }
interface ScheduledController { scheduledTime:number; cron:string; noRetry():void; }
interface Env { DB:D1Database; [key:string]:unknown; }
type Row=Record<string,unknown>;
const COOKIE="sas_contractor_v2",enc=new TextEncoder();
const txt=(v:unknown,n=240)=>String(v??"").trim().slice(0,n);
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;","&gt;":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
function cookie(req:Request){for(const p of (req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===COOKIE)return p.slice(i+1).trim()}return ""}
async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))),b=>b.toString(16).padStart(2,"0")).join("")}
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}
async function session(req:Request,env:Env){const t=cookie(req);if(!t)return null;return first(env,`SELECT s.company_id companyId,s.account_id accountId,a.full_name fullName,a.email,COALESCE(NULLIF(s.active_role,''),a.role) role,c.name companyName,c.licence_status licenceStatus,c.expires_at expiresAt,c.grace_days graceDays FROM contractor_sessions s JOIN contractor_accounts a ON a.id=s.account_id AND a.company_id=s.company_id JOIN companies c ON c.id=s.company_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND a.status='active' LIMIT 1`,[await hash(t)])}
function daysLeft(expiry:string,grace:number){const end=new Date(expiry).getTime()+grace*86400000;return Math.max(0,Math.ceil((end-Date.now())/86400000))}
function licencePage(s:Row){const status=txt(s.licenceStatus||"unknown").toLowerCase(),expiry=txt(s.expiresAt),grace=num(s.graceDays),days=daysLeft(expiry,grace),active=["active","trial"].includes(status);return new Response(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Company Licence · TMM Asset Health</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f6fb;color:#071a35;font-family:Arial,sans-serif}.wrap{max-width:1050px;margin:auto;padding:34px}.hero,.card{background:#fff;border:1px solid #d9e1eb;border-radius:14px}.hero{padding:22px;margin-bottom:16px}.hero small{font-size:10px;font-weight:900;letter-spacing:.08em;color:#66768d}.hero h1{margin:6px 0 0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{padding:18px}.card span,.card b{display:block}.card span{font-size:10px;color:#66768d;font-weight:900;text-transform:uppercase}.card b{font-size:22px;margin-top:8px}.pill{display:inline-block!important;padding:7px 11px;border-radius:999px;background:${active?"#e8f7ef":"#fff0f0"};color:${active?"#12643e":"#9b2020"};font-size:11px!important}.note{margin-top:16px;background:#fff;border:1px solid #d9e1eb;border-radius:12px;padding:16px;color:#5d6d84;font-size:12px;line-height:1.5}.back{display:inline-block;margin-top:16px;background:#132b4d;color:#fff;text-decoration:none;padding:10px 13px;border-radius:8px;font-weight:800;font-size:12px}@media(max-width:700px){.grid{grid-template-columns:1fr}.wrap{padding:18px}}</style></head><body><main class="wrap"><section class="hero"><small>COMPANY LICENCE</small><h1>${esc(s.companyName)}</h1></section><div class="grid"><section class="card"><span>Licence status</span><b><span class="pill">${esc(status.toUpperCase())}</span></b></section><section class="card"><span>Licence expiry</span><b>${esc(expiry?expiry.slice(0,10):"Not set")}</b></section><section class="card"><span>Grace period</span><b>${grace} day${grace===1?"":"s"}</b></section><section class="card"><span>Days remaining</span><b>${days}</b></section></div><div class="note">This page only shows the TMM Asset Health licence information needed by the customer. SARS, tax, identity and other personal/legal details are not displayed here.</div><a class="back" href="/contractor?view=settings">Back to Settings</a></main></body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
function injectLicenceNav(body:string){if(body.includes('href="/company-licence"'))return body;const link=`<a href="/company-licence"><span>▧</span><b>Licence</b></a>`;if(body.includes('<a class="active" href="/contractor?view=settings"'))return body.replace('<a class="active" href="/contractor?view=settings"',link+'<a class="active" href="/contractor?view=settings"');if(body.includes('href="/contractor?view=settings"'))return body.replace(/<a([^>]*href="\/contractor\?view=settings"[^>]*)>/,link+'<a$1>');return body}
function stripSensitiveCompanyDetails(body:string){return body
.replace(/<label[^>]*>[^<]*(?:SARS|Tax number|VAT number|ID number|Identity number)[\s\S]*?<\/label>/gi,"")
.replace(/<div[^>]*class="[^"]*(?:sars|tax-details|personal-details)[^"]*"[^>]*>[\s\S]*?<\/div>/gi,"");}
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url),s=await session(req,env);if(url.pathname==="/company-licence"&&req.method==="GET"){if(!s)return new Response(null,{status:303,headers:{location:"/contractor-login"}});return licencePage(s)}const res=await currentApp.fetch(req,env as never,ctx as never);if(req.method!=="GET")return res;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let body=await res.text();body=injectLicenceNav(body);if(url.pathname==="/contractor"&&["settings","setup"].includes(url.searchParams.get("view")||""))body=stripSensitiveCompanyDetails(body);const h=new Headers(res.headers);h.delete("content-length");h.set("cache-control","private, no-store");return new Response(body,{status:res.status,statusText:res.statusText,headers:h})},async scheduled(c:ScheduledController,env:Env,ctx:ExecutionContext){const app=currentApp as unknown as {scheduled?:(c:ScheduledController,e:Env,x:ExecutionContext)=>Promise<void>|void};if(app.scheduled)return app.scheduled(c,env,ctx)}};
