export interface TenantAuditEnv {
  DB: D1Database;
  ADMIN_PASSWORD?: string;
}

type Row = Record<string, unknown>;
function esc(v:unknown){return String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0;}
function html(body:string,status=200){return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tenant Isolation Audit · TMM Asset Health</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f7f8;color:#132235;font-family:Arial,Helvetica,sans-serif}.top{background:#061827;color:white;padding:18px 24px;border-bottom:4px solid #11975c}.top b{font-size:20px}.wrap{max-width:1080px;margin:26px auto;padding:0 18px}.card{background:white;border:1px solid #dce4e8;border-radius:12px;padding:20px;margin-bottom:14px}.brand{color:#11975c}.gold{color:#d99a00}.field{display:grid;gap:6px;font-size:12px;font-weight:800;max-width:520px}.field input{padding:11px;border:1px solid #cbd5dd;border-radius:8px}.btn{margin-top:12px;border:0;background:#11975c;color:white;border-radius:8px;padding:11px 16px;font-weight:800;cursor:pointer}.test{display:grid;grid-template-columns:80px 1fr;gap:10px;border-bottom:1px solid #eef2f4;padding:10px 0;font-size:12px}.pass{color:#087944;font-weight:900}.fail{color:#c92828;font-weight:900}.notice{background:#eaf7ef;color:#12643d;padding:12px;border-radius:8px;font-size:12px}.warn{background:#fff5df;color:#8b5c00;padding:12px;border-radius:8px;font-size:12px}.summary{font-size:30px;font-weight:900}.small{font-size:11px;color:#687685;line-height:1.5}code{background:#f2f5f7;padding:2px 5px;border-radius:4px}</style></head><body><div class="top"><b>Sindane Asset Solutions</b><div>TMM ASSET HEALTH · Owner Security Lab</div></div><main class="wrap">${body}</main></body></html>`,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'private, no-store','x-frame-options':'DENY','referrer-policy':'same-origin'}});}
async function first(env:TenantAuditEnv,sql:string,binds:unknown[]=[]){return await env.DB.prepare(sql).bind(...binds).first<Row>();}
async function count(env:TenantAuditEnv,sql:string,binds:unknown[]=[]){return n((await first(env,sql,binds))?.n);}
async function ensure(env:TenantAuditEnv){
  const statements=[
    `CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,licence_key TEXT NOT NULL UNIQUE,licence_status TEXT NOT NULL DEFAULT 'trial',expires_at TEXT NOT NULL,grace_days INTEGER NOT NULL DEFAULT 7,max_users INTEGER NOT NULL DEFAULT 10,created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS machines (id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,fleet_number TEXT NOT NULL,category TEXT NOT NULL,site TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'operating',operating_hours REAL NOT NULL DEFAULT 0,availability_target REAL NOT NULL DEFAULT 0.9,next_service_hours REAL,created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,fleet_number TEXT NOT NULL,event_type TEXT NOT NULL,severity TEXT NOT NULL,system_name TEXT NOT NULL,component TEXT NOT NULL,description TEXT NOT NULL,opened_at TEXT NOT NULL,closed_at TEXT,downtime_hours REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'open',action TEXT,spares_status TEXT,expected_return TEXT,oil_litres_lost REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS production_records (id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,report_date TEXT NOT NULL,fleet_number TEXT NOT NULL,shift_hours REAL NOT NULL DEFAULT 24,planned_downtime REAL NOT NULL DEFAULT 0,unplanned_downtime REAL NOT NULL DEFAULT 0,operating_hours REAL NOT NULL DEFAULT 0,productive_hours REAL NOT NULL DEFAULT 0,tonnes REAL NOT NULL DEFAULT 0,source_file TEXT,created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS work_orders (id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,fleet_number TEXT NOT NULL,title TEXT NOT NULL,priority TEXT NOT NULL,assigned_to TEXT,due_at TEXT,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS contractor_documents (id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,uploaded_by INTEGER NOT NULL,file_name TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,content_type TEXT,size_bytes INTEGER NOT NULL DEFAULT 0,category TEXT NOT NULL DEFAULT 'general',created_at TEXT NOT NULL)`
  ];
  for(const q of statements)await env.DB.prepare(q).run();
}
async function company(env:TenantAuditEnv,name:string,keyPrefix:string){
  let row=await first(env,'SELECT id FROM companies WHERE name=? LIMIT 1',[name]);
  if(!row){const now=new Date().toISOString(),exp=new Date(Date.now()+30*86400000).toISOString();const res=await env.DB.prepare('INSERT INTO companies(name,licence_key,licence_status,expires_at,grace_days,max_users,created_at) VALUES(?,?,?,?,?,?,?)').bind(name,`${keyPrefix}-${crypto.randomUUID()}`,'suspended',exp,0,5,now).run();row={id:Number(res.meta.last_row_id)};}
  const id=n(row.id);await env.DB.prepare("UPDATE companies SET licence_status='suspended' WHERE id=?").bind(id).run();return id;
}
async function seed(env:TenantAuditEnv,cid:number,prefix:string){
  const fleet=`${prefix}-TST-001`,now=new Date().toISOString(),today=now.slice(0,10);
  if(!(await first(env,'SELECT id FROM machines WHERE company_id=? AND fleet_number=? LIMIT 1',[cid,fleet])))await env.DB.prepare('INSERT INTO machines(company_id,fleet_number,category,site,status,operating_hours,availability_target,next_service_hours,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(cid,fleet,'Isolation Test Machine',`${prefix} Test Site`,'operating',100,0.9,350,now).run();
  if(!(await first(env,"SELECT id FROM events WHERE company_id=? AND fleet_number=? AND description='TENANT ISOLATION TEST' LIMIT 1",[cid,fleet])))await env.DB.prepare('INSERT INTO events(company_id,fleet_number,event_type,severity,system_name,component,description,opened_at,downtime_hours,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(cid,fleet,'test','low','Security','Tenant Scope','TENANT ISOLATION TEST',now,0.25,'open',now).run();
  if(!(await first(env,'SELECT id FROM production_records WHERE company_id=? AND fleet_number=? AND source_file=? LIMIT 1',[cid,fleet,'tenant-isolation-test'])))await env.DB.prepare('INSERT INTO production_records(company_id,report_date,fleet_number,shift_hours,planned_downtime,unplanned_downtime,operating_hours,productive_hours,tonnes,source_file,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(cid,today,fleet,24,0,0.25,8,7.5,prefix==='ALPHA'?111:222,'tenant-isolation-test',now).run();
  if(!(await first(env,"SELECT id FROM work_orders WHERE company_id=? AND fleet_number=? AND title='TENANT ISOLATION TEST JOB' LIMIT 1",[cid,fleet])))await env.DB.prepare('INSERT INTO work_orders(company_id,fleet_number,title,priority,assigned_to,due_at,status,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(cid,fleet,'TENANT ISOLATION TEST JOB','low','Security Audit',now,'open',now).run();
  const key=`company/${cid}/security-test/${prefix.toLowerCase()}-tenant-test.txt`;
  if(!(await first(env,'SELECT id FROM contractor_documents WHERE company_id=? AND object_key=? LIMIT 1',[cid,key])))await env.DB.prepare('INSERT INTO contractor_documents(company_id,uploaded_by,file_name,object_key,content_type,size_bytes,category,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(cid,0,`${prefix.toLowerCase()}-tenant-test.txt`,key,'text/plain',0,'security-test',now).run();
  return fleet;
}
type Test={name:string;pass:boolean;detail:string};
async function runAudit(env:TenantAuditEnv){
  await ensure(env);
  const alpha=await company(env,'[SECURITY TEST] Alpha Mining','ALPHA-SECURITY');
  const beta=await company(env,'[SECURITY TEST] Beta Mining','BETA-SECURITY');
  const af=await seed(env,alpha,'ALPHA'),bf=await seed(env,beta,'BETA');
  const tests:Test[]=[]; const add=(name:string,pass:boolean,detail:string)=>tests.push({name,pass,detail});
  add('Separate company IDs',alpha!==beta,`Alpha=${alpha}; Beta=${beta}`);
  add('Alpha machine visible to Alpha',await count(env,'SELECT COUNT(*) AS n FROM machines WHERE company_id=? AND fleet_number=?',[alpha,af])===1,af);
  add('Beta machine hidden from Alpha',await count(env,'SELECT COUNT(*) AS n FROM machines WHERE company_id=? AND fleet_number=?',[alpha,bf])===0,`Alpha query cannot return ${bf}`);
  add('Alpha machine hidden from Beta',await count(env,'SELECT COUNT(*) AS n FROM machines WHERE company_id=? AND fleet_number=?',[beta,af])===0,`Beta query cannot return ${af}`);
  add('Beta machine visible to Beta',await count(env,'SELECT COUNT(*) AS n FROM machines WHERE company_id=? AND fleet_number=?',[beta,bf])===1,bf);
  add('Events tenant-scoped',await count(env,'SELECT COUNT(*) AS n FROM events WHERE company_id=? AND fleet_number=?',[alpha,bf])===0&&await count(env,'SELECT COUNT(*) AS n FROM events WHERE company_id=? AND fleet_number=?',[beta,af])===0,'Cross-company event lookups return zero');
  add('Production tenant-scoped',await count(env,'SELECT COUNT(*) AS n FROM production_records WHERE company_id=? AND fleet_number=?',[alpha,bf])===0&&await count(env,'SELECT COUNT(*) AS n FROM production_records WHERE company_id=? AND fleet_number=?',[beta,af])===0,'Cross-company production lookups return zero');
  add('Work orders tenant-scoped',await count(env,'SELECT COUNT(*) AS n FROM work_orders WHERE company_id=? AND fleet_number=?',[alpha,bf])===0&&await count(env,'SELECT COUNT(*) AS n FROM work_orders WHERE company_id=? AND fleet_number=?',[beta,af])===0,'Cross-company work order lookups return zero');
  const ad=await first(env,'SELECT object_key AS objectKey FROM contractor_documents WHERE company_id=? AND category=? LIMIT 1',[alpha,'security-test']);const bd=await first(env,'SELECT object_key AS objectKey FROM contractor_documents WHERE company_id=? AND category=? LIMIT 1',[beta,'security-test']);
  add('Document key prefixes isolated',String(ad?.objectKey||'').startsWith(`company/${alpha}/`)&&String(bd?.objectKey||'').startsWith(`company/${beta}/`),`${ad?.objectKey} | ${bd?.objectKey}`);
  add('Alpha cannot select Beta document',await count(env,"SELECT COUNT(*) AS n FROM contractor_documents WHERE company_id=? AND object_key LIKE ?",[alpha,`company/${beta}/%`])===0,'Cross-company document query returns zero');
  add('Beta cannot select Alpha document',await count(env,"SELECT COUNT(*) AS n FROM contractor_documents WHERE company_id=? AND object_key LIKE ?",[beta,`company/${alpha}/%`])===0,'Cross-company document query returns zero');
  const tables=['machines','events','production_records','work_orders','contractor_documents'];
  let cols=true;for(const t of tables){const info=await env.DB.prepare(`PRAGMA table_info(${t})`).all<Row>();if(!(info.results||[]).some(r=>String(r.name)==='company_id'))cols=false;}
  add('Core operational tables contain company_id',cols,tables.join(', '));
  const alphaStatus=String((await first(env,'SELECT licence_status AS status FROM companies WHERE id=?',[alpha]))?.status);const betaStatus=String((await first(env,'SELECT licence_status AS status FROM companies WHERE id=?',[beta]))?.status);
  add('Test tenants remain suspended',alphaStatus==='suspended'&&betaStatus==='suspended','Neither test company can become a live customer accidentally');
  return {alpha,beta,tests,passed:tests.filter(t=>t.pass).length,total:tests.length};
}
export async function handleTenantIsolationAudit(request:Request,env:TenantAuditEnv):Promise<Response|null>{
  const url=new URL(request.url);if(url.pathname!=='/owner/tenant-isolation-test')return null;
  if(request.method==='GET')return html(`<section class="card"><h1>TMM Asset Health Tenant Isolation Audit</h1><p class="small">This owner-only security lab creates two suspended dummy tenants, <b>Alpha Mining</b> and <b>Beta Mining</b>, inserts distinct test machines/events/production/work-orders/document references, and verifies that tenant-scoped queries cannot cross the company boundary.</p><div class="warn">This is a database and storage-key isolation audit. Direct URL/API penetration testing remains a separate release gate.</div><form method="post"><label class="field">Sindane owner password<input type="password" name="password" required autocomplete="current-password"></label><button class="btn" type="submit">Run Alpha vs Beta Isolation Test</button></form></section>`);
  if(request.method!=='POST')return new Response('Method not allowed',{status:405});
  const f=await request.formData(),password=String(f.get('password')||'');if(!env.ADMIN_PASSWORD||password!==env.ADMIN_PASSWORD)return html(`<section class="card"><h1>Access denied</h1><p class="fail">The owner password was not accepted.</p><a href="/owner/tenant-isolation-test">Back</a></section>`,403);
  try{const r=await runAudit(env);return html(`<section class="card"><h1>Tenant Isolation Audit Result</h1><div class="summary ${r.passed===r.total?'pass':'fail'}">${r.passed}/${r.total} PASS</div><p class="small">Alpha company ID: ${r.alpha} · Beta company ID: ${r.beta}</p><div class="notice">Both security-test tenants are forced to <b>suspended</b> status after creation.</div></section><section class="card">${r.tests.map(t=>`<div class="test"><span class="${t.pass?'pass':'fail'}">${t.pass?'PASS':'FAIL'}</span><div><b>${esc(t.name)}</b><div class="small">${esc(t.detail)}</div></div></div>`).join('')}</section><section class="card"><h2>Release interpretation</h2><p class="small">A full pass proves the core D1 tenant filters and company-specific document key structure used by the contractor system. Before commercial release, also test direct URLs, exports, report endpoints, invitation acceptance, role escalation attempts and R2 downloads using two real test login sessions.</p></section>`);}catch(e){return html(`<section class="card"><h1>Audit error</h1><p class="fail">${esc(e instanceof Error?e.message:String(e))}</p></section>`,500);}
}
