interface Env{DB:D1Database;BUCKET?:R2Bucket;[key:string]:unknown}
type Row=Record<string,unknown>;type Session={companyId:number;accountId:number;role:string;fullName:string;companyName:string};
const COOKIE="sas_contractor_v2",enc=new TextEncoder();
const VIDEO_FILES:Record<string,string>={
  "getting-started":"01_Dashboard_and_Fleet.mp4",
  "fleet-sites":"01_Dashboard_and_Fleet.mp4",
  "daily-reports":"02_Daily_Reports.mp4",
  "breakdowns-alerts":"03_Breakdowns.mp4",
  "maintenance-service":"04_Maintenance.mp4",
  "purchase-orders":"08_Alerts.mp4",
  "reports-kpis":"06_Weekly_and_Monthly_Reports.mp4",
  "users-roles":"07_Users_and_Roles.mp4",
  "licence":"09_Report_Control.mp4",
  "telematics-oem":"10_Company_Setup_and_Settings.mp4",
  "ai-assistant":"11_TMM_AI_Assistant.mp4"
};
const txt=(v:unknown,n=500)=>String(v??"").trim().slice(0,n),num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
function cookie(req:Request){for(const p of(req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===COOKIE)return p.slice(i+1).trim()}return""}
async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))),b=>b.toString(16).padStart(2,"0")).join("")}
async function first(env:Env,sql:string,b:unknown[]=[]){try{return await env.DB.prepare(sql).bind(...b).first<Row>()}catch{return null}}
async function all(env:Env,sql:string,b:unknown[]=[]){try{return(await env.DB.prepare(sql).bind(...b).all<Row>()).results||[]}catch{return[]}}
async function session(req:Request,env:Env):Promise<Session|null>{const t=cookie(req);if(!t)return null;const r=await first(env,`SELECT s.company_id companyId,s.account_id accountId,COALESCE(NULLIF(s.active_role,''),a.role) role,a.full_name fullName,c.name companyName FROM contractor_sessions s JOIN contractor_accounts a ON a.id=s.account_id JOIN companies c ON c.id=s.company_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') AND a.status='active' LIMIT 1`,[await hash(t)]);return r?{companyId:num(r.companyId),accountId:num(r.accountId),role:txt(r.role,60).toLowerCase(),fullName:txt(r.fullName,120),companyName:txt(r.companyName,150)}:null}
async function ensure(env:Env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS tutorial_lessons_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,description TEXT NOT NULL,role_scope TEXT NOT NULL DEFAULT 'all',video_url TEXT,enabled INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS tutorial_progress_v1(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,account_id INTEGER NOT NULL,lesson_id INTEGER NOT NULL,completed INTEGER NOT NULL DEFAULT 0,completed_at TEXT,updated_at TEXT NOT NULL,UNIQUE(company_id,account_id,lesson_id))`).run();const lessons=[["getting-started","Company Admin Getting Started","Understand the dashboard, navigation, alerts and daily workflow.","company_admin,admin",1],["fleet-sites","Register Sites and Fleet","Add sites, register machines and import a fleet spreadsheet.","company_admin,admin,engineer",2],["daily-reports","Daily Reports","Upload or manually capture reports using Time or Hour Meter.","all",3],["breakdowns-alerts","Breakdowns and Alerts","Record breakdowns and review critical, high and repeated-failure alerts.","company_admin,admin,engineer,mechanic,supervisor,manager",4],["maintenance-service","Maintenance and Service Status","Manage service intervals, hour-meter warnings, plans and job cards.","company_admin,admin,engineer,mechanic,manager",5],["purchase-orders","PO and Parts Tracking","Track ordered parts, suppliers, responsible people and overdue delivery.","company_admin,admin,engineer,manager",6],["reports-kpis","Weekly, Monthly and KPI Reports","Understand availability, utilisation, production, downtime and Pareto reports.","company_admin,admin,engineer,supervisor,manager",7],["users-roles","Users, Roles and Invitations","Invite users, assign roles and understand company access.","company_admin,admin",8],["licence","Company Licence","View licence status, expiry and printable certificate.","company_admin,admin,manager",9],["telematics-oem","Telemetry and OEM Mapping","Create connections, map external machine IDs and review condition data.","company_admin,admin,engineer,mechanic",10],["ai-assistant","Using the TMM AI Assistant","Ask questions, use voice input, attach photos and understand read-only safety.","all",11]];const now=new Date().toISOString();for(const l of lessons)await env.DB.prepare(`INSERT INTO tutorial_lessons_v1(slug,title,description,role_scope,video_url,enabled,sort_order,created_at,updated_at) VALUES(?,?,?,?,NULL,1,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,description=excluded.description,role_scope=excluded.role_scope,sort_order=excluded.sort_order,updated_at=excluded.updated_at`).bind(l[0],l[1],l[2],l[3],l[4],now,now).run()}
function redirect(p:string){return new Response(null,{status:303,headers:{location:p,"cache-control":"no-store"}})}
function css(){return `<style>*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:#10203a;font-family:Arial,sans-serif}.top{background:#071827;color:#fff;padding:16px 5%;display:flex;justify-content:space-between}.top a{color:#fff;text-decoration:none;font-weight:800}.wrap{max-width:1180px;margin:auto;padding:22px}.hero{background:linear-gradient(135deg,#071827,#08764b);color:#fff;border-radius:16px;padding:23px}.hero h1{margin:5px 0}.hero small{color:#e5ae12;font-weight:900;letter-spacing:1px}.progress{height:10px;background:#dfe7ed;border-radius:99px;overflow:hidden;margin-top:12px}.progress span{display:block;height:100%;background:#0b995d}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin-top:14px}.card,.panel{background:#fff;border:1px solid #dce4ed;border-radius:13px;padding:17px}.card{display:flex;flex-direction:column}.card h2{font-size:16px;margin:8px 0}.card p{font-size:12px;color:#657386;line-height:1.5;flex:1}.num{width:35px;height:35px;border-radius:50%;background:#e9f6ef;color:#087548;display:grid;place-items:center;font-weight:900}.status{font-size:10px;font-weight:900;color:#a66900}.status.done{color:#087548}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 13px;background:#0b7a4b;color:#fff;text-decoration:none;font-weight:900;font-size:11px;cursor:pointer}.video{aspect-ratio:16/9;background:#071827;border-radius:13px;display:grid;place-items:center;color:#fff;text-align:center;padding:20px;margin:14px 0;overflow:hidden}.video video{width:100%;height:100%}.steps{line-height:1.7;font-size:13px}.notice{background:#fff7dd;border-left:4px solid #e5ad12;padding:12px;font-size:12px;border-radius:8px}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.grid{grid-template-columns:1fr}.wrap{padding:12px}}</style>`}
function allowed(scope:string,role:string){return scope==="all"||scope.split(",").map(x=>x.trim()).includes(role)}
async function centre(env:Env,s:Session){const lessons=(await all(env,`SELECT l.*,COALESCE(p.completed,0) completed FROM tutorial_lessons_v1 l LEFT JOIN tutorial_progress_v1 p ON p.lesson_id=l.id AND p.company_id=? AND p.account_id=? WHERE l.enabled=1 ORDER BY l.sort_order`,[s.companyId,s.accountId])).filter(l=>allowed(txt(l.role_scope),s.role));const done=lessons.filter(l=>num(l.completed)===1).length,pct=lessons.length?Math.round(done/lessons.length*100):0;return new Response(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>TMM Tutorial Centre</title>${css()}</head><body><header class="top"><b>TMM Asset Health Training</b><a href="/contractor">← Dashboard</a></header><main class="wrap"><section class="hero"><small>SINDANE ASSET SOLUTIONS</small><h1>Tutorial Centre</h1><p>Role-specific training for ${esc(s.fullName)} · ${esc(s.role)}</p><div class="progress"><span style="width:${pct}%"></span></div><p>${done} of ${lessons.length} lessons completed · ${pct}%</p></section><div class="grid">${lessons.map((l,i)=>`<article class="card"><div class="num">${i+1}</div><h2>${esc(l.title)}</h2><p>${esc(l.description)}</p><div class="status ${num(l.completed)===1?"done":""}">${num(l.completed)===1?"✓ COMPLETED":VIDEO_FILES[txt(l.slug)]?"VIDEO AVAILABLE":"VIDEO COMING SOON"}</div><p><a class="btn" href="/tutorials/lesson/${esc(l.slug)}">Open Lesson</a></p></article>`).join("")}</div></main></body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
async function lesson(env:Env,s:Session,slug:string){const l=await first(env,`SELECT l.*,COALESCE(p.completed,0) completed FROM tutorial_lessons_v1 l LEFT JOIN tutorial_progress_v1 p ON p.lesson_id=l.id AND p.company_id=? AND p.account_id=? WHERE l.slug=? AND l.enabled=1 LIMIT 1`,[s.companyId,s.accountId,slug]);if(!l||!allowed(txt(l.role_scope),s.role))return new Response("Lesson not found",{status:404});const file=VIDEO_FILES[txt(l.slug)]||"";const video=file?`/tutorials/media/${encodeURIComponent(file)}`:"";return new Response(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(l.title)}</title>${css()}</head><body><header class="top"><b>TMM Tutorial Centre</b><a href="/tutorials">← All Lessons</a></header><main class="wrap"><section class="panel"><small>ROLE TRAINING · ${esc(s.role)}</small><h1>${esc(l.title)}</h1><p>${esc(l.description)}</p><div class="video">${video?`<video controls preload="metadata" src="${esc(video)}"></video>`:`<div><b>Tutorial video coming soon</b><p>The lesson structure is ready. The recorded TMM walkthrough will be attached here.</p></div>`}</div><div class="notice">Use test data during training. Never display passwords, API keys or confidential mine information.</div><h2>Lesson outcome</h2><ol class="steps"><li>Understand where this function is located.</li><li>Follow the correct TMM workflow.</li><li>Review information before saving.</li><li>Know when engineering or administrator confirmation is required.</li></ol><form method="post" action="/tutorials/complete"><input type="hidden" name="lessonId" value="${num(l.id)}"><button class="btn" type="submit">${num(l.completed)===1?"Mark as Incomplete":"Mark Lesson Complete"}</button></form></section></main></body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
async function media(env:Env,file:string){
  if(!env.BUCKET)return new Response("Tutorial storage unavailable",{status:503});
  if(!Object.values(VIDEO_FILES).includes(file))return new Response("Video not found",{status:404});
  const obj=await env.BUCKET.get(`tutorials/${file}`);
  if(!obj)return new Response("Video not found",{status:404});
  const h=new Headers();
  h.set("content-type",obj.httpMetadata?.contentType||"video/mp4");
  h.set("content-length",String(obj.size));
  h.set("cache-control","private, max-age=3600");
  h.set("content-disposition",`inline; filename="${file.replace(/["\\r\\n]/g,"")}"`);
  h.set("x-content-type-options","nosniff");
  return new Response(obj.body,{headers:h});
}
export async function handleTutorialCentre(req:Request,env:Env):Promise<Response|null>{
  const u=new URL(req.url),p=u.pathname;
  if(p!=="/tutorials"&&!p.startsWith("/tutorials/"))return null;
  const s=await session(req,env);if(!s)return redirect("/contractor-login");
  if(p.startsWith("/tutorials/media/")&&req.method==="GET")return media(env,decodeURIComponent(p.slice("/tutorials/media/".length)));
  try{await ensure(env)}catch{return new Response("Tutorial Centre is temporarily unavailable. The main TMM software remains operational.",{status:503})}
  if(p==="/tutorials"&&req.method==="GET")return centre(env,s);
  if(p.startsWith("/tutorials/lesson/")&&req.method==="GET")return lesson(env,s,decodeURIComponent(p.slice("/tutorials/lesson/".length)));
  if(p==="/tutorials/complete"&&req.method==="POST"){
    const f=await req.formData(),id=num(f.get("lessonId"));
    const l=await first(env,"SELECT id,role_scope scope FROM tutorial_lessons_v1 WHERE id=? AND enabled=1",[id]);
    if(!l||!allowed(txt(l.scope),s.role))return new Response("Lesson not found",{status:404});
    const old=await first(env,"SELECT completed FROM tutorial_progress_v1 WHERE company_id=? AND account_id=? AND lesson_id=?",[s.companyId,s.accountId,id]),done=num(old?.completed)===1?0:1,now=new Date().toISOString();
    await env.DB.prepare(`INSERT INTO tutorial_progress_v1(company_id,account_id,lesson_id,completed,completed_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(company_id,account_id,lesson_id) DO UPDATE SET completed=excluded.completed,completed_at=excluded.completed_at,updated_at=excluded.updated_at`).bind(s.companyId,s.accountId,id,done,done?now:null,now).run();
    return redirect("/tutorials")
  }
  return new Response("Method not allowed",{status:405})
}
